### ISSUE TITLE
clang-latest now generates `-Wextra-semi-stmt` in unit tests

### ISSUE THREAD

**Issue by AndrewPaxie** [rollbear/trompeloeil#107]
Daily compile of Trompeloeil unit tests with `clang-latest` shows this warning generated:

```text
test/compiling_tests_11.cpp:245:24:
warning: empty expression statement has no effect;
remove unnecessary ';' to silence this warning [-Wextra-semi-stmt]
    INFO("msg=" << msg);
                       ^
```

63 warnings total.

Using Catch version 2.2.3.
Same errors occur with Catch 2.4.2, released 26 October 2018.

Warning was 'refined' in this Clang/LLVM commit

```text
commit 0d4609da69d513b7737d2f932e3db6e57f7b11c3
Author: Roman Lebedev <lebedev.ri@gmail.com>
Date:   Tue Nov 20 18:59:05 2018 +0000

:::

    Fixes [[ https://bugs.llvm.org/show_bug.cgi?id=39111 | PR39111 ]]
    
:::
```

### What to do

Some options:

- Remove the semicolon in Trompeloeil test cases.
- Raise an issue with Catch team asking for a fancier `INFO` macro.
- Disable the warning in the build.

**Comment by AndrewPaxie** [comment]
The issue is with Catch2: `WARN` and `CAPTURE` macros expect a semicolon
to terminate them (see `INTERNAL_CATCH_MSG`, `INTERNAL_CATCH_CAPTURE`).
`INFO` forwards to `INTERNAL_CATCH_INFO` which has a trailing semicolon.

The examples in the Catch documentation are also inconsistent, with semicolon
terminating `INFO` in some examples and no semicolon terminating `INFO` in
other examples.  All examples require a semicolon.

Will raise an issue with the Catch project, if one doesn't already exist.

**Comment by AndrewPaxie** [comment]
Raise issue in Catch project: <https://github.com/catchorg/Catch2/issues/1456>.

**Comment by rollbear** [comment]
Added `-Wno-extra-semi-stmt` to `self_test` target, for clang compilers that supports it, so that we can build clean with clang-8. It's a pity, but not a big issue.
