### ISSUE TITLE
Using with Networking TS

### ISSUE THREAD

**Issue by RedDwarf69** [rollbear/trompeloeil#109]
I have been trying to use trompeloeil for literally just a couple of hours. So this is more a question than an issue. Sorry, I didn't find a better place.

I want to use a Mock as an ASIO/Networking TS Handler. For example a ReadHandler (https://www.boost.org/doc/libs/develop/doc/html/boost_asio/reference/ReadHandler.html). This has two requirements:
- It needs to be MoveConstructible
- It must be callable

trompeloeil complains when I try to mock `operator()`. I didn't see this mentioned anywhere in the docs (I may have missed it). But I see I can do:

```
class MockHandler
{
public:
  MAKE_MOCK1(Functor, void(const error_code& ec));
  void operator()(const error_code &ec) {return Functor(ec);}
};
```

So, maybe this could be fixed/documented?

But the important one: when I try to use it in a Networking TS Initiating Function it complains because it seems to fail because the Mock class is not MoveConstructible and not even CopyConstructible. Again, I have not seen this mentioned in the docs. Is it fixable?

**Comment by RedDwarf69** [comment]
I guess the MoveConstructible thing is a silly request (how to check the expectations later?).
Leaving this open, though, since I would like to know if my workaround to implement the operator() mock is the best available. And if so, maybe it can be added to the FAQ / CookBook?

**Comment by toby-allsopp** [comment]
I don't think having MoveConstructible mock classes is silly at all. In fact, I was just about to create an issue requesting the same thing.

It's perhaps not obvious how to handle the expectations - do they move with mock object, stay on the moved-from object or both? Perhaps making it customisable via a traits class or something would be feasible? Then the test-writer could choose between move (e.g. unique_ptr), shared (e.g. shared_ptr) or some other copying policy.

**Comment by RedDwarf69** [comment]
Bad form or not, what I would argue is that if an user is going to start moving stuff around then he is supposed to think about that kind of stuff, it's not a trompeloeil specific issue. Nice if it is, but doesn't even _need_ to be documented in trompeloeil.

But are we supposing Mocks are Movable by default? If an user wants to explicitly make a Mock non-Movable... is trompeloeil going to help with the syntax, or it's expected that the user will explicitly `= delete` the move constructor? I'm fine with the later, but it's worth explicitly mentioning it somewhere.

Then, two things:
* I _am_ using trompeloeil with Networking TS
I needed to create some reference wrappers, but it does work. So... it would be easier if the Mocks would be directly movable, but don't do it just to support Networking TS.

* Are you planning to support Movable Mocks... only if somehow the Mock ends back into the user control so he can check the expectations? In the Networking TS case I give the Mock to the initiating function and I never get it back. To be able to check the expectations I may need some kind of `ExpectationChecker checker = mock.getExpectationsChecker()` so I can move away the mock, but keeping the ExpectationChecker with me.

**Comment by rollbear** [comment]
For now, I will add documentation describing that mocks aren't movable or copyable, and why.

If I can figure out a way to do this with unsurprising semantics, I'll change it. The behaviour is not terrible if you know that the expressions in your `WITH`, `RETURN`, `SIDE_EFFECT`, etc, are lambdas that the mock object has pointers to,  but to a casual user that is not obvious.

**Comment by rollbear** [comment]
I've had a partial change of heart, here. You can play with it on branch `move_mock`. Currently not
documented at all. There are nasty corners here that needs to be documented if this is to make it into `master`, so let me know all your findings. I think I'd preferably have some way of explicitly enabling move construction, since at least I had some surprising results that led me to single step the expectation list logic in the debugger so I could fix my example test.

**Comment by rollbear** [comment]
More done now. There's a PR #111 you can look at. I'm thinking that an explicit opt-in can work, and by default a compilation error message that provides info about the situation, and how to opt in.

Please do try this out, and provide feedback.

**Comment by rollbear** [comment]
I would like to close this one now, since mocks can be move constructed in just recently tagged release v33. Anyone opposing this?

**Comment by rollbear** [comment]
It is indeed a limitation. I'll add it, and the work-around, to the FAQ.

**Comment by RedDwarf69** [comment]
Reading https://github.com/rollbear/trompeloeil/blob/master/docs/reference.md/#movable_mock I got a bit confused with this:

`when a mock object is moved, any current expectations will be taken over by the newly constructed mock object`

I guess this mean that the expectations now look at what member functions of the moved-to object are being called, they don't look at the moved-from object
But the wording seems to imply that the expectation lifetime depends on the lifetime of the mock object, that the mock "owns" the expectation.
Maybe I got expectations lifetimes wrong. But their lifetime doesn't depend on the mock object, right? If they are named the lifetime depends on the lifetime of the unique_ptr and if they are unnamed their lifetime ends with their scope, right?


`If the lifetime of an expectation is associated with the life of the moved-from object`

Again, I may have gotten the expectations lifetimes wrong. But the lifetime of an expectation is never associated with the life of either the moved-from or moved-to object, is it?


Also, the formatting of the new question in the FAQ seems to be wrong and the question is difficult to see: https://github.com/rollbear/trompeloeil/blob/master/docs/FAQ.md#move_constructible

**Comment by rollbear** [comment]
Thank you for this feedback. It is surprisingly difficult to find the right wording, it seems. From your questions, I get the impression that you have indeed understood it correctly. I just have to figure out a better way to explain it.

1. Any expectations that were on the moved-from object, will be on the newly created object, i.e. any ´REQUIRE_CALL´, etc, will be on the member functions for the new object.
2. Lifetimes of expectations are unrelated to lifetimes of mock objects. You have this absolutely right. The issue I was trying to get to was this:
   ```Cpp
   Mock setup() {
     Mock obj;
     REQUIRE_CALL(obj, func());
     return obj;
     // expectation dies here, unsatisfied, causing a test failure.   
   }
   ```
   Using named expectations makes this more visible, I think.

**Comment by rollbear** [comment]
Updated reference manual with the example above, and also fixed the formatting issue in the FAQ, plus added entry in cookbook on mocking `operator()`. Help for further improved wording would be appreciated.

**Comment by RedDwarf69** [comment]
mocks can be used as Networking TS completion handlers by simply wrapping them with std::ref, we now have movable mocks also anyway and the `operator()` limitation is documented. Seems ready to be closed to me.
