### ISSUE TITLE
"Integrating with unit test frame works" documentation could be improved

### ISSUE THREAD

**Issue by RedDwarf69** [rollbear/trompeloeil#118]
Reading https://github.com/rollbear/trompeloeil/blob/master/docs/CookBook.md#unit_test_frameworks, specifically the "Compile time adapter" section, one would reach the conclusion that this code would compile:

```
#define TROMPELOEIL_USER_DEFINED_COMPILE_TIME_REPORTER
#include "trompeloeil.hpp"

namespace trompeloeil
{
  template <>
  void reporter<specialized>::send(
    severity s,
    const char* file,
    unsigned long line,
    const char* message)
  {
    return;
  }
}
```

But it fails to compile, complaining about "specialization after instantiation".

Also, if I am an user looking for how to integrate with Catch I'm unlikely to read the "Compile time adapter" section. I will directly go to https://github.com/rollbear/trompeloeil/blob/master/docs/CookBook.md#adapt_catch which fails to mention TROMPELOEIL_USER_DEFINED_COMPILE_TIME_REPORTER. The exact same problem exists for all the other sample adaptations.

**Comment by rollbear** [comment]
Thanks. Yes, this is bad.

**Comment by rcdailey** [comment]
I thought I mentioned this in another issue a year or two ago, but I can't find it. I remember throwing around the idea of a 'contrib' package of header files that each provide integration with a specific test framework. I think that would be a lot more useful than maintaining documentation that people essentially have to copy & paste from.

**Comment by barneydellar** [comment]
I've only looked at the section for Catch (https://github.com/rollbear/trompeloeil/blob/master/docs/CookBook.md/#adapt_catch) , but it is wrong. 

I used this in a single translation unit instead: 
```
auto unused = trompeloeil::set_reporter([](
    trompeloeil::severity s,
    char const *file,
    unsigned long line,
    std::string const &msg
) {
    std::ostringstream os;
    if (line) os << file << ':' << line << '\n';
    os << msg;
    auto failure = os.str();
    if (s == trompeloeil::severity::fatal)
    {
        FAIL(failure);
    }
    else
    {
        CAPTURE(failure);
        CHECK(failure.empty());
    }
});
```
and it worked fine. I didn't need to extern anything. Updating the docs would definitely help newcomers!

I am using Visual Studio 2017 15.9.7, and Catch2 v2.7.0.

**Comment by rollbear** [comment]
What's your opinion on this? I'm not happy about it, but it does tell you what to do. This is for Catch2 only, but similar phrasing would be added to the others:

--%<---

***Adapter for Catch2***

If your test program has one single [translation unit] http://stackoverflow.com/questions/8342185/ddg#8342233),
paste the following code snippet in global namespace:

```Cpp
  namespace trompeloeil
  {
    template <>
    void reporter<specialized>::send(
      severity s,
      const char* file,
      unsigned long line,
      const char* msg)
    {
      std::ostringstream os;
      if (line) os << file << ':' << line << '\n';
      os << msg;
      auto failure = os.str();
      if (s == severity::fatal)
      {
        FAIL(failure);
      }
      else
      {
        CAPTURE(failure);
        CHECK(failure.empty());
      }
    }
  }
```

If you have several [translation units](http://stackoverflow.com/questions/8342185/ddg#8342233),
paste the above in global namespace of one of them, and in all other
translation units, make sure the macro
`TROMPELOEIL_USER_DEFINED_COMPILE_TIME_REPORTER` is defined before
`#include <trompeloeil.hpp>`. Adding this macro to the compilation via the
build system will be less intrusive to your code. *Note!* that you
can unfortunately not define the macro in the translation unit that implements
the `trompeloeil::reporter<specialized>::send()` function.

--%<---

I have long thought about @rcdailey's suggestion to add wrapper headers, like `<catch2/trompeloeil.hpp>`, which would include `trompeloeil.hpp` and add the adapter. I think this is good. What's your opinion regarding the obvious dependency to `catch.hpp`, though? On the one hand, it makes sense to include it from the wrapper, but then the problem becomes the include path. Not including it places a header inclusion order dependency, which is quite unpleasant.

**Comment by rollbear** [comment]
I just pushed to an experimental branch `adapters`, support for adapter headers for 5 unit testing frameworks. The way these work is very simple. If you're using catch, your test translation units begins with

```Cpp
#include <catch.hpp>
#include <catch/trompeloeil.hpp>
...
```
If you're using [`doctest`](https://github.com/onqtam/doctest), your test translation units begins with

```Cpp
#include <doctest.h>
#include <doctest/trompeleil.hpp>
...
```

As far as I've been able to test them, it works fine. Please give it a whirl. So far the documentation does not reflect this change, but I'll work on it later today.

**Comment by barneydellar** [comment]
I haven’t tried compiling with the adapters branch, but it looks good! It looks like it will be much easier for a beginner to get started.

**Comment by AndrewPaxie** [comment]
I like the direction this is going.

I never used the `extern template` method in
projects where I have used Trompeloeil, preferring
the ["Borland model"](
https://gcc.gnu.org/onlinedocs/gcc-3.3.6/gcc/Template-Instantiation.html) of inline
template function definitions you have adopted for `reporter<specialized>::send()`.

I wonder if there is room in the documentation for an "exemplar"
implementation separate from all the specific cases.  I first learned
about this form of documentation in Vinnie Falco's CppCon 2017
talk: ["Make Classes Great Again!"](
https://www.youtube.com/watch?v=WsUnnYEKPnI) (Thanks Vinnie!)

I will be contributing the an adapter for
[CxxTest](http://cxxtest.com/) once this new layout
makes it to `master`.

As a follow-on to this, I recently had to mix both compile-time
and runtime adapters, to test the adapter itself.  Here's an outline
of the code I used:

```cpp
namespace trompeloeil {

template <>
inline
void reporter<specialized>::send(
    severity s,
    const char* file,
    unsigned long line,
    const char* msg)
{
    using ReporterSig = typename std::decay<decltype(default_reporter)>::type;

    auto reporter = reporter_obj().target<ReporterSig>();

    if (reporter && *reporter == default_reporter)
    {
        /* There is no overriding runtime reporter adaptor. */
        std::ostringstream os;

        if (line)
        {
            os << file << ':' << line << '\n';
        }

        os << msg;

        auto failure = os.str();

        if (s == severity::fatal)
        {
            // Must not return normally i.e. must throw, abort or terminate.
            FATAL_ACTION(failure);
        }
        else
        {
            // nonfatal: violation occurred during stack rollback.
            // Must not throw an exception.
            NON_FATAL_ACTION(failure);
        }
    }
    else
    {
        /* Defer to the non-default runtime reporter adaptor. */
        reporter_obj()(s, file, line, msg);
    }
}

} /* namespace trompeloeil */
```

where `FATAL_ACTION(failure)` and `NON_FATAL_ACTION(failure)`
are unspecified but perform the actions required for the test framework
to be informed of `failure`.

Possibly this is a separate issue?  Just wanted to get the code out
sooner than later.

**Comment by amanjitgill** [comment]
I also had a problem with this section of the documentation 
 https://github.com/rollbear/trompeloeil/blob/master/docs/CookBook.md/#adapt_catch

The type `reporter_func `uses a `std::string const&` as last parameter, while the documentation mentions `const char*`, so it does not  compile until you change the snippet to use std::string  (VS 2015)

**Comment by rollbear** [comment]
D'oh! :man_facepalming: Thank you @amanjitgill . Fixed on the `adapters` branch now. And sorry @mattgodbolt for not understanding what problem your PR solved.

**Comment by rollbear** [comment]
I like the idea of a concrete example @AndrewPaxie. I'll just use one of the included ones.

**Comment by rollbear** [comment]
I think I'm done with updating the docs and the include directory structure now. Please have a look at:

https://github.com/rollbear/trompeloeil/blob/adapters/docs/CookBook.md#unit_test_frameworks

and tell me what needs more work.

**Comment by rollbear** [comment]
The updated include structure and rewritten docs has now landed in tagged release v34, so closing now.
