### ISSUE TITLE
Is it possible to set expectations for a mock in a helper function?

### ISSUE THREAD

**Issue by amanjitgill** [rollbear/trompeloeil#127]
Hello,

Can I set expections in a function, that I can call from several tests ? It seems that the REQUIRE_CALLs are immediately validated at the end of this helper function? I may be doing something wrong.  

void setViewExp(MockView& view) {
    REQUIRE_CALL(view, showView()).TIMES(AT_LEAST(1));
    REQUIRE_CALL(view, enableButtonX(false)).TIMES(AT_LEAST(1));
}

Thanks

**Comment by rollbear** [comment]
Indeed, lifetime of expectations follow the [scope rules](https://github.com/rollbear/trompeloeil/blob/master/docs/CookBook.md#setting_expectations) of C++ (this is a feature!) To extend the the lifetime of expectations beyond the current scope, use [**`NAMED_REQUIRE_CALL`**](https://github.com/rollbear/trompeloeil/blob/master/docs/reference.md/#NAMED_REQUIRE_CALL)
and be explicit in your code about the lifetime of your expectation objects.

**Comment by amanjitgill** [comment]
Thanks!
