### ISSUE TITLE
Rename library to something simple

### ISSUE THREAD

**Issue by rcdailey** [rollbear/trompeloeil#13]
For us Americans that only speak 1 language, I find it incredibly tedious and frustrating to use and remember this library's name and namespace.

Could you go with a simpler namespace name, such as `tmock`? I mean no offense, I just think when it comes to APIs, simplicity and convenience is key.

**Comment by memsharded** [comment]
Partly agree, but acknowledge that naming is difficult, especially when many names, namespaces, urls... are already taken. Plus the name has meaning for the author, so even if I find it (very) difficult to spell and write, I understand and can live with it.

**Comment by rollbear** [comment]
Thank you @rcdailey  for your interest, and @memsharded  for your input.

Given that French is one of the many languages I don't speak (see #11)  I partly sympathize, and partly not (see [FAQ](https://github.com/rollbear/trompeloeil/blob/master/docs/FAQ.md#why_name)).

I'm open to suggestions, although I do prefer something with a bit of humour and elegance.

While thinking about it, though, may I suggest a very simple work-around for you?:

Create a file `tmock.hpp` (if tmock if your preferred name.)
```Cpp
#ifndef TMOCK_HPP
#define TMOCK_HPP

#include <trompeloeil.hpp>
namespace tmock = trompeloeil;

#endif /* include guard */
```

After this, you can `#include <tmock.hpp>` and use `tmock::deathwatched<>`, etc.

Having said this, I personally find this no more difficult than a password. Awkward at first, but after a few attempts its in muscle memory and nothing you really think of anymore.

**Comment by rcdailey** [comment]
Certainly a reasonable workaround. If taking action on the library side is not possible, I would certainly use this as a next step.

**Comment by Mistress-Anna** [comment]
For us non-american people, I find it incredibly tedious and frustrating to have to learn american for everything in computing, not just simple library names.

There'll always be people who will struggle with a library name (or anything) which is not in their native language (except maybe if all libraries are named in variations of "aaaaaaa"), it's not just you, rest assured.

Also, if the name has some kind of uniqueness, I think it's easier to remember. "tmock" is so generic that I'm surprised there aren't already a dozen libs called like that. "trompeloeil" on the other hand...

**Comment by rcdailey** [comment]
tmock would be an alias to make using the library easier. Not its new name.

**Comment by rollbear** [comment]
No need to start a war here.

Like I mentioned earlier, I'm open to suggestions, otherwise I would've closed this issue.

My personal take is that a name like `tmock` is too generic, and quite frankly boring, but to each his own. But then, it's easy to create your own alias if you need to, so guess it's not a big issue.

**Comment by mlimber** [comment]
I'm partial to `trompe` as the alias. Easy to say, remember, and spell since all the Frenchy-ness that confuses English speakers is snipped off. Also, it means "[deceive](https://en.wiktionary.org/wiki/tromper#French)", which is makes it awesome.

**Comment by AndrewPaxie** [comment]
I like the name Trompeloeil - it gives the project a certain _je ne sais quoi_.

That said, I also appreciate the `using namespace` tip in the FAQ and suggested here in the comments.

**Comment by rcdailey** [comment]
I'm going to go ahead and close my own issue here. I apparently worded my original post poorly, as things have become political. My intent was to express that I am not familiar with non-american / non-english names, not to send some strange and subliminal political message.

The solution of using an alias (namespace) is sufficient for my needs. I have an include file I use to simulate this:

tmock.h:

```
#pragma once
#include <trompeloeil.hpp>
namespace tmock = trompeloeil;
```

This is per [an earlier suggestion](https://github.com/rollbear/trompeloeil/issues/13#issuecomment-233466400) made by @rollbear. Thanks to those who provided constructive feedback.
