### ISSUE TITLE
How can I set a parameter passed by reference to my mock?

### ISSUE THREAD

**Issue by Gomox11** [rollbear/trompeloeil#130]
Hello!

I mocked a read method which takes a buffer as its parameter.

`void Read(Buffer& buffer)`

The data gets written into the buffer which is passed by reference.

I'm calling this method from within another method which I'm currently testing. The method under test passes one of its members (it's the buffer) as reference to the Read method. Now I want to add something to my REQUIRE_CALL macro that will set the value of the buffer which is passed by reference. I only know about the RETURN macro which doesn't help here.

`TEST_CASE("MyPseudoTestCase");`
`REQUIRE_CALL(MockedClass, Read(_)).SET(<FIRST PARAMETER TO "abc">)`
`ClassUnderTest.SomeMethod();`

Does anyone have any idea on how to set the buffer with the mocked method?

Thanks in advance!

**Comment by rollbear** [comment]
Does [**`.SIDE_EFFECT()`**](https://github.com/rollbear/trompeloeil/blob/master/docs/reference.md#SIDE_EFFECT)
not work?

**Comment by Gomox11** [comment]
> Does [**`.SIDE_EFFECT()`**](https://github.com/rollbear/trompeloeil/blob/master/docs/reference.md#SIDE_EFFECT)
> not work?

How would I tell SIDE_EFFECT to change the member of the ClassUnderTest? From what I know I can only tell SIDE_EFFECT to change variables that I either create in the test itself or are accessable in the class under test.

**Comment by rollbear** [comment]
I thought you wanted to change the parameter in the call, `buffer` in you  example? Is that not it?

**Comment by Gomox11** [comment]
> I thought you wanted to change the parameter in the call, `buffer` in you example? Is that not it?

Yes, I want to change buffer. Inside class 'A' I have something like:

```
void WriteBufferToInbox() {
  B.Read(buffer_);
  PostToInbox(buffer_.data());
}

```
And class 'B' takes the member variable buffer_ as reference.

`void Read(Buffer& buffer);`

So my test knows nothing about the member buffer_.

```
TEST_CASE("Test") {
  REQUIRE_CALL(B, Read(_));
  A.WriteBufferToInbox();
}
```

Which is why I don't know how to tell trompeloeil to "change the first parameter passed to Read to 'abc' ".

**Comment by rollbear** [comment]
`.SIDE_EFFECT(_1 = "abc")`, or `.SIDE_EFFECT(_1.some_member_function("abc"))`.

**Comment by Gomox11** [comment]
> `.SIDE_EFFECT(_1 = "abc")`, or `.SIDE_EFFECT(_1.some_member_function("abc"))`.

Oh wow, I didn't know one can use placeholders with references that way in SIDE_EFFECT. I'll give this a go and tell you how it went. Thanks for the quick replies :)

**Comment by Gomox11** [comment]
Works perfectly! Thanks so much for your help :)

**Comment by Audiodroid** [comment]
> `.SIDE_EFFECT(_1 = "abc")`, or `.SIDE_EFFECT(_1.some_member_function("abc"))`.

I think this would be good to have somewhere in the docs/faq/cookbook. It took me quiet a while to find this. SIDE_EFFECT has no example that alters a parameter passes by reference.
