### ISSUE TITLE
RETURN a structured binding

### ISSUE THREAD

**Issue by JoshCollins746** [rollbear/trompeloeil#136]
I have a catch2 test that tries to use the RETURN macro to return a copy of a local variable that is initialised in a structured binding. This code compiles on GCC and MSVC but fails on clang (tested 6, 7 and 8 on godbolt).

I have created a reproduction of the issue on godbolt here: https://godbolt.org/z/zm49h8

The warning is that we are trying to make a binding to a local reference which I guess is because structured bindings are implemented as references to an unnamed instance of the returned type. I am not sure if this is a genuine issue in the trompeloeil implementation or if it is something to do with clang but I thought I would report thisso that someone with more knowledge of the implementation might be able to investigate.

**Comment by JoshCollins746** [comment]
On further investigation it seems that it is actually just an issue with lambda capture of structured binding which seems to be currently ill-formed as per the discussions here:

https://stackoverflow.com/questions/46114214/lambda-implicit-capture-fails-with-variable-declared-from-structured-binding

It seems clang is being more strictly compliant than the other 2 compilers so perhaps there is no way to avoid this in c++17.

**Comment by rollbear** [comment]
That is my understanding too. It took me a bit longer than you to find it. I have a vague memory that this has been discussed as a standard defect, but I have not been able to find any reference to that.

**Comment by JoshCollins746** [comment]
One of the answers in the linked stack over flow discussion points to this:

http://www.open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#2313

I guess that there is not anything that can be done in trompeloeil, I will close the issue and keeps my fingers crossed that c++20 might resolve this!
