### ISSUE TITLE
Integrate with doctest/catch `-s` option

### ISSUE THREAD

**Issue by RedDwarf69** [rollbear/trompeloeil#137]
You can run doctest/catch generated tests runners with the `-s` option, which makes it print all the assertions even if they didn't fail. I like to use that option in my CI, to have a better view of what happened if there ever a problem and to help with reviewing.

The problem is that this "print passed assertions" option doesn't get passed to trompeloeil, making some of the output more confusing than useful (the only assert in some tests is the trompeloeil one).

I don't think there is any way to make this work currently, but I don't see why it couldn't be done. I guess:
- trompeloeil needs a way to let the user input this information
- catch/doctest need a way to export this information

Once trompeloeil does its part it would be easier to convince catch/doctest to add theirs.

**Comment by rollbear** [comment]
Maybe I misunderstand, but I don't see how this is possible. How should a mocked function, with no expectations and no calls, be reported? That is, arguably, a passed assertion. Is a `.ALLOW_CALL(...)` an assertion, and if so, how many? One for each call? `.TIMES(1,5)`?

**Comment by RedDwarf69** [comment]
You may be right. I have not really though too much about the details. I was thinking only about a simple `REQUIRE_CALL` without anything else.

In general I guess what I would like is a "This could have failed here, but it didn't".
So
`ALLOW_CALL(mock_obj, func(_)).RETURN(_1 + 1);`
only reports a failure if `mock_obj.func()` is called at least once returning something different than `_1 + 1`.

If `-s` is used it would print
```
<filename>:<line no>: PASSED:
  ALLOW_CALL(mock_obj, func(_)).RETURN(_1 + 1);
```
or, in a magic world, 
```
<filename>:<line no>: PASSED:
  ALLOW_CALL(mock_obj, func(_)).RETURN(_1 + 1);
details:
  Called two times
    #1 input 1, output 2
    #2 input 4, output 6
```

And I guess I would like this to be printed under the exact doctest subcase where the expectation is written. This is my main issue with the current situation, the output of doctest with "-s" seems to say the subcase doesn't even exist when the only assertion inside the subcase in a trompeloeil `REQUIRE_CALL`.

But yeah, may be it's simply a problem without solution. Feel free to close the issue if you don't come one with some brilliant idea.

**Comment by rollbear** [comment]
I understand what you mean, and I've wanted to find a solution myself, but failed. I'm not saying there isn't one, only that I haven't been able to figure one out. So, closing now. Feel free to reopen if some neat idea pops up. I like the thought, I just don't understand how it can be implemented.
