### ISSUE TITLE
Compile time vs runtime reporter

### ISSUE THREAD

**Issue by rcdailey** [rollbear/trompeloeil#14]
Correct me if I'm wrong, but it seems like when utilizing multiple translation units in a single test executable, the runtime reporter (calling `set_reporter`) is more desirable since I can do the reporter setup in 1 translation unit. Whereas the compile time approach requires including the specialized reporter class in each translation unit along with trompeloeil itself.

**Comment by rollbear** [comment]
Ah, bug.

The compile time approach works (at least with Linux and gcc or clang) when the TU with the specialized reporter class is the last on the linker line. This seems brittle, though.

You're right in your analysis. Thanks.

**Comment by rcdailey** [comment]
FWIW, I was building under MSVC 14 compiler. It does not have such ordering dependencies. When placing the specialized class in 1 of my translation units, tests executed from another translation unit resulted in an abort because the specialization was not found. This makes sense, since the specialization is not in the header and won't be found by the compiler.

So I'll stick with the runtime approach.

**Comment by rollbear** [comment]
I won't have access to a windows development machine until after the weekend, but if you have the time, would you please try this out and tell me how it works?

In all TUs but one, add the line:
```Cpp
extern template struct trompeloeil::reporter<trompeloeil::specialized>;
```
In one TU, reformat the compile time specialization as:
```Cpp
namespace trompeloeil
{
  template <>
  void reporter<specialized>::send(severity s,
                                   const char* file,
                                   unsigned long line,
                                   const char* msg)
  {
      ...
  }
}
```

This works with clang++ (3.6 and later) and g++ (4.9 and later.)

**Comment by rollbear** [comment]
Just verified that this does work with VS too. I'll update the docs.

**Comment by rollbear** [comment]
Closing this now since docs are updated in release of v18.
