### ISSUE TITLE
Conan installation requires prebuild package

### ISSUE THREAD

**Issue by offa** [rollbear/trompeloeil#144]
The first installation of this package via conan fails, because it can not find any prebuild packages – although the library is header-only and shouldn't need one.

## Minimal Example
_(Make sure Trompeloeil isn't in the cached already)_

There's no source code needed, just a `conanfile.txt`.

### conanfile.txt:

```
[requires]
trompeloeil/v34@rollbear/stable

[generators]
cmake_find_package
cmake_paths
```

### Steps to reproduce:

```sh
mkdir build && cd build
conan install ..
```

### Build log:

```
trompeloeil/v34@rollbear/stable: Not found in local cache, looking in remotes...
trompeloeil/v34@rollbear/stable: Trying with 'conan-center'...
Downloading conanmanifest.txt
[==================================================] 604B/604B        
Downloading conanfile.py
[==================================================] 867B/867B        
trompeloeil/v34@rollbear/stable: Downloaded recipe revision 0
conanfile.txt: Installing package
Requirements
    trompeloeil/v34@rollbear/stable from 'conan-center' - Downloaded
Packages
    trompeloeil/v34@rollbear/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Missing

trompeloeil/v34@rollbear/stable: WARN: Can't find a 'trompeloeil/v34@rollbear/stable' package for the specified settings, options and dependencies:
- Settings: 
- Options: 
- Dependencies: 
- Package ID: 5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9

ERROR: Missing prebuilt package for 'trompeloeil/v34@rollbear/stable'
Try to build it from sources with "--build trompeloeil"
Or read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package"
```

## Expected

The package shouldn't require a build. 

Unfortunately I don't understand why it even needs one. The according to the [docs](https://docs.conan.io/en/latest/howtos/header_only.html?#without-unit-tests), the`conanfile.py` is totally fine.

## Workaround:

Build the package:

```sh
conan install .. -b missing
```

This gives a warning:

```
trompeloeil/v34@rollbear/stable: Calling build()
trompeloeil/v34@rollbear/stable: WARN: This conanfile has no build step
```

But the package is cached now and a further installations will work without the `-b missing`.

-----------------------
##### Update:
The "_WARN: This conanfile has no build step_" warning  seems to be normal.

**Comment by rollbear** [comment]
A very reasonable expectation, I think. What version of `conan` are you using?

**Comment by offa** [comment]
I'm using 1.15.1. I just noticed that there's v1.16, so I'm going to update it.

**Comment by offa** [comment]
The [header only conan template](https://github.com/bincrafters/conan-templates/blob/master/header_only/conanfile.py#L40) uses this:

```py
def package_id(self):
    self.info.header_only()
```

**Comment by offa** [comment]
I can't find where the package is build and uploaded :confused:

**Comment by Boulougou** [comment]
`v28` was the last one that contained a pre-built package (https://dl.bintray.com/trompeloeil/trompeloeil/rollbear/trompeloeil/v28/stable/0/package/).

Versions after that (e.g. https://dl.bintray.com/trompeloeil/trompeloeil/rollbear/trompeloeil/v34/stable/0/) do not have any package uploaded, so conan users needs to build the package locally.

It is simple to build the package locally, but it is inconvenient especially for CI scripts which assume that all conan packages are readily available in conan center.

**Comment by Boulougou** [comment]
Uploading the built package in conan-center, e.g:

```
conan upload trompeloeil/v34@rollbear/stable --all -r=conan-center
```
would resolve the issue, but it requires write permission in conan-center.

**Comment by rollbear** [comment]
Can you check if v35 works for you? I have the weirdest access problems with conan, where one machine (the one I build on) refuses any contact with conan-center, and an ancient machine appears to succeed. I wish I understood the difference between the two.

**Comment by Boulougou** [comment]
>Can you check if v35 works for you?
It works. Just tried it and it successfully downloaded the package.

**Comment by rollbear** [comment]
Thanks. I'll try to re-upload the others during the weekend.

**Comment by offa** [comment]
v35 works for me. :+1:
