### ISSUE TITLE
Missing reporting of successful tests

### ISSUE THREAD

**Issue by ToreMartinHagen** [rollbear/trompeloeil#159]
Catch2 has a framework to report number of assertions and list which test cases it has ran. This does not work with REQUIRE_CALL in trompeloeil.

Given a test in catch2 like this

```
SCENARIO("Foo test")
{
    WHEN("foo called"){
        THEN("call barfunc"){
            REQUIRE_CALL(bar, barfunc(5, ANY(int))).RETURN(4);
            foo.foo(5, 6);
        }
    }
}
```

When running the test it will be reported as this:
```
=======================================================
test cases: 1 | 1 passed
assertions: - none -
```
If you run the test with the -s option to include  successful tests in output you get the same output as above

It would be good if there was a hook so that Catch2 also sees the requirements that Trompeloeil sets. The output should then be like this for a normal test

```
======================================================
All tests passed (1 assertion in 1 test case)
```

If you run the test with -s option it should print out something like this:
```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
footest is a Catch v2.8.0 host application.
Run with -? for options

-------------------------------------------------------------------------------
Scenario: Foo test
       When: foo called
       Then: call barfunc
-------------------------------------------------------------------------------
/scratch/mytest/FooTest.cpp:50
...............................................................................

/scratch/mytest/trompeloeil/include/catch2/trompeloeil.hpp:52: PASSED:
  REQUIRE( trompeloeil_mock_calls_done_correctly != 0 )
with expansion:
  "bar.barfunc(5, ANY(int))" != 0

==========================================================
All tests passed (1 assertion in 1 test case)
```

**Comment by rollbear** [comment]
It's a nice idea, but there are some situations I don't know how to report.

* How should an `ALLOW_CALL(...)` be counted?
* How should a `FORBID_CALL(...)` be counted? If counted at all, does that mean all mocked functions that do not have any expectations should be counted? 

Related, and more generalized (and perhaps slightly absurd), how should `REQUIRE_CALL(...).TIMES(2,6)` be counted?

**Comment by ToreMartinHagen** [comment]
In the implementation I tested I added a call to `report_match(e.active)` in `mock_func` if we don't call the `report_mismatch(...)`. This then ends up as REQUIRE("bar.barfunc(5, ANY(int))" != 0);

For `ALLOW_CALL(...)` and `REQUIRE_CALL(...).TIMES(2,6)` this comes out as a number of passed tests like this

`/scratch/onetechmain/qt/test/TestHelpers/trompeloeil/include/catch2/trompeloeil.hpp:52: PASSED:
  REQUIRE( trompeloeil_mock_calls_done_correctly != 0 )
with expansion:
  "bar.barfunc(5, ANY(int))" != 0

/scratch/onetechmain/qt/test/TestHelpers/trompeloeil/include/catch2/trompeloeil.hpp:52: PASSED:
  REQUIRE( trompeloeil_mock_calls_done_correctly != 0 )
with expansion:
  "bar.barfunc(5, ANY(int))" != 0

/scratch/mytest/trompeloeil/include/catch2/trompeloeil.hpp:52: PASSED:
  REQUIRE( trompeloeil_mock_calls_done_correctly != 0 )
with expansion:
  "bar.barfunc(5, ANY(int))" != 0

===============================================================================
All tests passed (3 assertions in 1 test case)
`
For `FORBID_CALL(...)` I have to test some more...

**Comment by ToreMartinHagen** [comment]
Have submitted a pull request #165. 

If the `FOBIDEN_CALL(...)` expectation is met (function not called) there is no output. So that can be seen as a further improvement. For me the number of `FORBIDEN_CALL `is very small compared to the number of `REQUIRE_CALL`

**Comment by rollbear** [comment]
Closing now as this is included in the v36 release.
