### ISSUE TITLE
Help: Can trompeloeil mock C functions?

### ISSUE THREAD

**Issue by jamespharvey20** [rollbear/trompeloeil#16]
Need to add a mock library to my unit tests.

All of my development is c++14, so I like the looks of trompeloeil, but I do use the MySQL c connector. I have database classes that use it internally, and would like to mock out the MySQL c connector library.

I'd like to avoid writing an abstract base class defining an interface to the MySQL library, with a class inheriting from it that uses the MySQL c connector, and another being a mock class. I'd prefer to be able to mock the actual MySQL c functions, so I don't leave the derived class that uses the MySQL c connector untested, admittedly it would basically be a straight passthrough.

Can trompeloeil help with this, or do I need to look for another mock library or use pre-processor or linker methods for C functions?

I looked through the examples and issues, and don't see anything showing mocking c functions, but wanted to ask before I assumed it can't do it.

**Comment by rollbear** [comment]
Trompeloeil mocks member functions only. The rest is up to your ingenuity.

If you can live with using a link seam, it's quite easy, though, and I do it a lot.

```Cpp
// c_header.h
int func1(int);
void func2(const char*);
```

```cpp
// mock_c_header.h
#include <c_header.h>
#include <trompeloeil.hpp>

class c_mock
{
public:
  static c_mock*& instance() { static c_mock* m = nullptr; return m;}
  c_mock() { assert(!instance()); instance() = this; }
  ~c_mock() { assert(instance() == this); instance() = nullptr);
  c_mock(const c_mock&) = delete;

  MAKE_MOCK1(func1, int(int));
  MAKE_MOCK1(func2, void(std::string)); // makes life easier
};
```

Then you make your own implementation to link with, rather than the real library:

```Cpp
// mock_c_impl.cpp
#include "mock_c_header.h"

int func1(int i)
{
  return c_mock::instance()->func1(i);
}

void func2(const char* s)
{
  c_mock::instance()->func2(s);
}
```

Now, in your tests:

```Cpp
#include "mock_c_header.h"
TEST("MyClass calls func1 when poked")
{
  c_mock api;
  MyClass tested;
  {
    REQUIRE_CALL(api, func1(trompeloeil::gt(100))
      .RETURN(-_1);
    tested.poke(3); // better call mock_c_impl version of int func1(int)
  }
}
```

**Comment by jamespharvey20** [comment]
Excellent, thanks!  I'm on my way, having success mocking the C library.

**Comment by rollbear** [comment]
I think I should add this to the FAQ. Thanks.
