### ISSUE TITLE
Elegant way of moving REQUIRE_CALL to function

### ISSUE THREAD

**Issue by Gomox11** [rollbear/trompeloeil#163]
Hello!

Inside my test cases, I often times have to use a bunch of REQUIRE_CALL statements. Some of them could be grouped together with an expressive method name and moved out of the test case itself. However, REQUIRE_CALL is limited to its scope which means that moving it into a function causes an error on running the test.

Is there any elegant solution to this? Thanks in advance!

**Comment by rollbear** [comment]
It depends on your definition of elegant, I guess. One thing I've done a few times is to write a function that returns a vector of expectations, like this:

```Cpp
auto setup(...)
{
  std::vector<trompeloeil::expectation> rv;
  rv.push_back(NAMED_REQUIRE_CALL(obj1, func(...)));
  rv.push_back(NAMED_REQUIRE_CALL(obj2, func(...)).WITH(_1 == arg1));
  ...
  return rv;
}

TEST(...)
{
  ...
  auto expectations = setup(objs..., args...);
  ... // exercise your unit under test
}
```

**Comment by Gomox11** [comment]
That's pretty elegant indeed :D Thanks for sharing.

**Comment by rollbear** [comment]
Should be `std::vector<std::unique_ptr<trompeloeil::expectation>>`. Sorry for that.
