### ISSUE TITLE
Cannot mock classes that return tuples

### ISSUE THREAD

**Issue by domainerror** [rollbear/trompeloeil#164]
Example:
```C++
struct S
{
    // Numerous clang errors, including
    // "Cannot initialize return object of type 'int' with an rvalue of type 'trompeloeil::matcher *'"
    // "No member named 'size' in 'std::__1::tuple<int>'"
    MAKE_MOCK0(func, std::tuple<int, double>());
};
void q()
{
}
```
If the tuple takes one type, it works.

No ideas on this one, other than the fact that it's curious that the second error claims a tuple defined different to the one actually declared...

**Comment by rollbear** [comment]
It's a sad effect of how the preprocessor works. It thinks the macro is invoked with 3 parameters:
`func`, `std::tuple<int` and `double>()`. To work around it, you can use an alias type, or a parenthesize the return type, as described in the [CookBook](https://github.com/rollbear/trompeloeil/blob/master/docs/CookBook.md#mocking_return_template).

I should probably add this example to the FAQ.

**Comment by domainerror** [comment]
Thanks for the reference (sorry for missing that in the cookbook). Interestingly, the example in that section fails for me:
```C++
struct M
{
  MAKE_MOCK2(make, (std::pair<int,int>(int,int)));
};
```
It's accompanied by numerous clang errors, including:
- Expected ';' after alias declaration
- Template argument for template type parameter must be a type
- Unknown type name 'trompeloeil_l_matcher_list_t_35'

However, the type alias did work.

**Comment by rollbear** [comment]
Ops, bug in the example! It should be

```Cpp
struct M
{
  MAKE_MOCK2(make, (std::pair<int,int>)(int,int));
};
```

I'll fix this tonight.

**Comment by domainerror** [comment]
That's what I thought, but the parenthesized return type technique fails for me, too.

**Comment by rollbear** [comment]
I'm confused. What differs from https://gcc.godbolt.org/z/YgtBG6 ?

**Comment by domainerror** [comment]
Ah, I was on a slightly out-of-date header. I was on ea89d9cb. With the latest source, the example compiles!

Thanks so much for your help!
