### ISSUE TITLE
Reading the new "Status OK reporting" docs leaves me with questions

### ISSUE THREAD

**Issue by RedDwarf69** [rollbear/trompeloeil#168]
https://github.com/rollbear/trompeloeil/commit/ca5cd1c85ef0ed8bf975a4f837bb5ff26441b362 looks cool, but I have read the documentation and I'm not sure I understood it completely.

It says `will be called if an expectation is met`. By "expectation" I understand anything under https://github.com/rollbear/trompeloeil/blob/master/docs/reference.md#expectation, which includes `FORBID_CALL`. But `FORBID_CALL` is not part of the tests in that commit, and I'm not really sure whether it's included.
I'm also unsure about what happens with the equivalent `REQUIRE_CALL(...).TIMES( 0 )` (is this going to make it _pass_ a `CATCH_REQUIRE`??). Or with TIMES(3), `LR_WITH`, etc.

**Comment by rollbear** [comment]
Ping @ToreMartinHagen

**Comment by ToreMartinHagen** [comment]
Hi.

It is correct that `FORBID_CALL` and `REQUIRE_CALL(...).TIMES( 0 )` are not included.  `TIMES(3)` or `TIMES(2,4)` are handled correctly. If you call the function 3 times then both will report 3 assertions, if you call it 2 times the first will fail and the second will report 2 assertions.

I started to look into how I could handle `FORBID_CALL`, but have not found a solution yet.

**Comment by rollbear** [comment]
I think the functionality is fine. You cannot count how many times a `FORBID_CALL` didn't fail the test ;-)

But probably the documentation can be improved to make the functionality easier to understand.

**Comment by ToreMartinHagen** [comment]
I will make an update of the document describing that `FORBID_CALL` and `REQUIRE_CALL(...).TIMES( 0 )` are not handled.

**Comment by rollbear** [comment]
For me, a description like "counts the number of times a call to a mocked function did not fail the test" would help, and then `FORBID_CALL` and `.TIMES(0)` can be added as examples to the explanation. Actually, a code snippet with examples would probably go a very long way.

**Comment by ToreMartinHagen** [comment]
Hi.

Here is a proposal to a new version of Status OK reporting. Please correct or comment as you please.

### Status OK reporting
It is possible to make an adaption to the reporter that will be called if
a positive expectation is met. This can be useful for correct counting and reporting
from the testing framework. Negative expectations like `FORBID_CALL` and
`.TIMES(0)` are not counted. 

Provide an inline specialization of the
`trompeloeil::reporter<trompeloeil::specialized>::sendOk()` function.
The function should call a matcher in the testing framework that always
yields true.

Below, as an example, is the adapter for the Catch2 unit testing frame
work, in the file <catch2/trompeloeil.hpp>

```Cpp
  template <>
  inline void reporter<specialized>::sendOk(
    const char* trompeloeil_mock_calls_done_correctly)
  {      
      REQUIRE(trompeloeil_mock_calls_done_correctly != 0);
  }
```

Below is a simple example for *Catch2*:

```Cpp
class MockFoo
{
public:
    MAKE_MOCK0(func, void());
};

TEST_CASE("Foo test")
{
    MockFoo foo;
    REQUIRE_CALL(foo, func()).TIMES(2,4);
    foo.func();
    foo.func();
}
```

When the test is executed we get the following output
```sh
$ ./footest
===============================================================================
All tests passed (2 assertions in 1 test case)
```

**Comment by RedDwarf69** [comment]
Looks clear to me.

**Comment by ToreMartinHagen** [comment]
submitted in pull request #170

**Comment by rollbear** [comment]
I assume this one's done.
