### ISSUE TITLE
For RETURN char*, do you have to define it and LR_RETURN it?

### ISSUE THREAD

**Issue by jamespharvey20** [rollbear/trompeloeil#17]
I'm mocking a C library I have no control over, so I can't just change the return value into a string.  This is reduced code.

Compiling:
```
#include <catch.hpp>
#include <trompeloeil.hpp>
using namespace trompeloeil;

class mock_c_mysql {
   public:
      MAKE_MOCK0(mysql_error, char*());
};

TEST_CASE("") {
   mock_c_mysql c_mysql;
   REQUIRE_CALL(c_mysql, mysql_error())
      .RETURN("Something");
   c_mysql.mysql_error();
}
```

Using gcc 6.2.1 gives errors:

```
In file included from /home/jharvey/code/tests/libs/pcdb/testPcdb.cpp:2:0:
/home/jharvey/code/thirdParty/trompeloeil.git/trompeloeil.hpp: In instantiation of ‘trompeloeil::call_modifier<Matcher, modifier_tag, trompeloeil::return_injector<typename trompeloeil::return_of<typename Parent::signature>::type, Parent> > trompeloeil::call_modifier<Matcher, modifier_tag, Parent>::handle_return(H&&) [with H = ____C_A_T_C_H____T_E_S_T____10()::<lambda(auto:24&)>; Matcher = trompeloeil::call_matcher<char*(), std::tuple<> >; modifier_tag = mock_c_mysql::trompeloeil_tag_type_trompeloeil_7; Parent = trompeloeil::matcher_info<char*()>; typename trompeloeil::return_of<typename Parent::signature>::type = char*]’:
/home/jharvey/code/tests/libs/pcdb/testPcdb.cpp:13:8:   required from here
/home/jharvey/code/thirdParty/trompeloeil.git/trompeloeil.hpp:2278:7: error: static assertion failed: RETURN value is not convertible to the return type of the function
       static_assert(is_illegal_type || matching_ret_type || void_signature,
       ^~~~~~~~~~~~~
/home/jharvey/code/thirdParty/trompeloeil.git/trompeloeil.hpp:2655:5: error: ‘static void trompeloeil::call_matcher<Sig, Value>::set_return(std::false_type, T&&) [with T = ____C_A_T_C_H____T_E_S_T____10()::<lambda(auto:24&)>; Sig = char*(); Value = std::tuple<>; std::false_type = std::integral_constant<bool, false>]’, declared using local type ‘____C_A_T_C_H____T_E_S_T____10()::<lambda(auto:24&) ’, is used but never defined [-fpermissive]
     set_return(std::false_type, T&&) //   RETURN
     ^~~~~~~~~~
```

If I change the `REQUIRE_CALL` line to:

```
char something[] = "Something\0";
REQUIRE_CALL(c_mysql, mysql_error())
   .LR_RETURN(something);
```

It compiles and works properly.

Hoping I've missed a way to avoid a local variable for a `char*`, as I'll have a lot of these.  `.LR_RETURN("Something");` doesn't work either.

**Comment by rollbear** [comment]
Not near a computer now,  but not allowing a string literal as `char*` makes sense,  since the string literal is `const char[]`, decaying to `const char*`. If you know with certainty that the returned string won't be modified, you can cast it in the return `. RETURN((char*) "hello")`.  Otherwise you need a modifiable buffer elsewhere that you can return.

**Comment by jamespharvey20** [comment]
ARGH.  You're absolutely right.  mysql_error even returns a `const char*`, and I somehow missed the `const`.

Your solution does work.  Fixing the mock to return type `const char*` also works.

Is there any easy way for the trompeloeil `static_assert`s to also show both the RETURN value and the return type of the function?  Along the lines of also including a "invalid conversion from `const char*' to `char*'" type error.

**Comment by rollbear** [comment]
Hmm.  The static_assert must get a string literal, and I don't see how I could generate one with that information. I'll see what other techniques I can use to make the compiler give more info without while still avoiding the classic 1000-line template error message avalanche.

**Comment by rollbear** [comment]
If you checkout the latest commit from the develop branch, there's a minor change that on g++-5.4 does provide slightly better information, although I must admit it's quite hidden.

**Comment by rollbear** [comment]
Updated develop again. The previous try was no good. Now it's not as good as you wished for, but you get
`RETURN const* from function returning pointer to non-const` which I think is reasonably informative. Also a synonymous one for references: `RETURN const& from function returning non-const reference`.

**Comment by jamespharvey20** [comment]
Thanks!  Works in gcc 6.2.1.

**Comment by rollbear** [comment]
Documented this in the FAQ for just tagged stable v19, so closing now.
