### ISSUE TITLE
TIMES macro fails to compile with many arguments.

### ISSUE THREAD

**Issue by Khadmium** [rollbear/trompeloeil#171]
Following code causes static assertion_error: 
Error: static assertion failed: Only one TIMES call limit is allowed, but it can express an interval

       ALLOW_CALL(mock, sum())
            .LR_SIDE_EFFECT(someFunction(5))
            .LR_RETURN(sumResult)
            .TIMES(2,3); // the same error with TIMES(AT_LEAST(5));
I think this is not intended, and confusing, because it is intended for calls like .TIMES(5).TIMES(5)
Also there is no issue with REQUIRE_CALL in the same scenario.

**Comment by rollbear** [comment]
Yes, it's not entirely ideal. It'd be better if the static assert explicitly stated that you can't use `.TIMES()` with `ALLOW_CALL()`,

What would `ALLOW_CALL(...).TIMES(2,3)` mean?

The static assert is a result of `ALLOW_CALL(...)` being a direct translation to `REQUIRE_CALL(...).TIMES(0, ~0ULL)`.

**Comment by Khadmium** [comment]
Thanks for fast replay.
It is not so obvious when taking into account that any call is forbidden by default,
so after invocation it is allowed to call it two or three times. 

> ALLOW_CALL(...) being a direct translation to REQUIRE_CALL(...).TIMES(0, ~0ULL).

Maybe it is worth mentioning in Cook Book, that any ALLOW_CALL, FORBID_CALL  is just an alias to some REQUIRE_CALL().TIMES(...) call. That information should clarify why "duplicated TIMES" static assertion error occurs in such scenario.
