### ISSUE TITLE
Setting expectation with THROW requires return value to be default constructable

### ISSUE THREAD

**Issue by laudrup** [rollbear/trompeloeil#172]
It seems like setting an expectation with THROW on a non-void function requires the functions return value to be default-constructable:

```
#include <catch.hpp>
#include <catch2/trompeloeil.hpp>

#include <exception>
#include <string>

class non_default_constructable {
public:
    non_default_constructable(const std::string& str) : str_(str) {}
private:
    const std::string str_;
};

class mocked_class {
public:
    MAKE_MOCK0(foo, non_default_constructable());
};

TEST_CASE("test non-default construtable") {
    mocked_class mock;
    REQUIRE_CALL(mock, foo()).RETURN(non_default_constructable{"foo"}); // Works
    REQUIRE_CALL(mock, foo()).THROW(std::runtime_error{"Whoops!"}); // Error. Return value is not default constructrable
    CHECK(true);
}
```

I don't really know if there's a workaround for this, apart from making whatever type returned default constructable which is a bit of a shame.

Am I missing something or is this a "missing feature"?

Thanks a lot and thanks a lot for you work with this very useful library.

**Comment by rollbear** [comment]
I will have to think about this. Intuitively it feels impossible, but maybe I can figure out a way.

**Comment by laudrup** [comment]
Thanks for the very quick response.

As a quick improvement, it might make sense to add a `static_assert` to `throw_handler_t`. Something like:

`static_assert(std::is_default_constructible<R>::value, "Return value must be default-constructible");`

Just tried it and IMO it does make the error slightly more understandable. I can create a pull request if you want?

**Comment by rollbear** [comment]
I agree, but let me think about this for a couple of days.

**Comment by laudrup** [comment]
Sure. Just wanted to offer my help if I could :-)

**Comment by rollbear** [comment]
Feel free to do a PR if you want to, but prepare to wait a few days before I act on it, and the act may be to drop it.

**Comment by rollbear** [comment]
After a fair amount of head scratching, the solution turned out to be simple, embarrassingly trivial even. Fixed on master now. I'm leaving the issue open until a release has been tagged.

**Comment by laudrup** [comment]
That was indeed quite simple. Thanks a lot for the fix.

I would personally think a compiler intrinsic (eg. `__builtin_unreachable()` for GCC) might be more explicit if that would work, but it's you project of course :-)

Thanks once again.

**Comment by rollbear** [comment]
Closing now as the fix is included in release v36.
