### ISSUE TITLE
Access violation when using std::string_view parameters

### ISSUE THREAD

**Issue by dgehri** [rollbear/trompeloeil#173]
When using a mocked method having a `std::string_view` parameter, if the expectation fails, an access violation is generated due to dereferencing a null pointer.

The reason is that  `is_null` is called as shown below, and the `nullptr` at the right of the comparison operator is converted to `std::string_view`, producing the access violation (MSVC 2019):

 ```
 template <typename T>
  inline
  constexpr
  bool
  is_null(
    T const &t,
    std::true_type)
  noexcept(noexcept(std::declval<const T&>() == nullptr))
  {
    return t == nullptr;
  }
```

**Comment by dgehri** [comment]
Note that the following template specialization solves the issue:

```
namespace trompeloeil {
template <>
constexpr bool is_null<std::string_view>(std::string_view const& t, std::true_type) noexcept { return t.empty(); }
}
```

**Comment by rollbear** [comment]
Thanks. I'll have to rethink this null-check thing. Doing these specializations are a work-around, not a solution.

**Comment by rollbear** [comment]
Can you try this diff? I think it's OK, but I need to add more tests before pushing a fix.

```diff
diff --git a/include/trompeloeil.hpp b/include/trompeloeil.hpp
index 0bd3f50..285afc8 100644
--- a/include/trompeloeil.hpp
+++ b/include/trompeloeil.hpp
@@ -1074,6 +1074,11 @@ template <typename T>
     char fill;
   };
 
+  struct indirect_null
+  {
+    constexpr operator std::nullptr_t() const { return nullptr; }
+  };
+
   template <typename T, typename U>
   using equality_comparison = decltype((std::declval<T>() == std::declval<U>())
                                        ? true
@@ -1083,7 +1088,7 @@ template <typename T>
   using is_equal_comparable = is_detected<equality_comparison, T, U>;
 
   template <typename T>
-  using is_null_comparable = is_equal_comparable<T, std::nullptr_t>;
+  using is_null_comparable = is_equal_comparable<T, indirect_null>;
 
   template <typename T>
   inline
```

**Comment by dgehri** [comment]
Thanks. I can confirm that this fixes the issue!

**Comment by rollbear** [comment]
This one is trickier than it appeared. The above patch works for all versions of clang that I've tried, and MSVC too, but it fails for all versions of gcc.

**Comment by rollbear** [comment]
I have a partial fix on master now. It works for clang, for gcc versions 5 and newer, and for MSVC 15 and newer. Unfortunately gcc 4.x and MSVC 14 still have the old behaviour. Hopefully this does not cause problems for many users.

**Comment by AndrewPaxie** [comment]
I cannot help but wonder if some further tweaks can be made to
continue support for earlier compiler versions.

I made this change in `test/compiling_tests.cpp`, moving function

```cpp
friend bool operator==(const char*, uncomparable_string) = delete;
```

to after the `class uncomparable_string` definition:

```cpp
bool operator==(const char*, uncomparable_string) = delete;
```

This results in all configurations with `g++` compiler to pass,
including these configurations that previously failed compilation:

`g++-4.9 -std=c++14 libstdc++-v3`\
`g++-4.9 -std=c++11 libstdc++-v3`\
`g++-4.9 -std=c++11 libc++`\
`g++-4.8 -std=c++11 libstdc++-v3`

They previously failed with this error:

```text
test/compiling_tests.hpp:228:62: error: can’t initialize friend function ‘operator==’
   friend bool operator==(const char*, uncomparable_string) = delete;
                                                              ^
```

The following configurations still fail to compile:

`clang++-3.8 -std=c++14 libstdc++-v3`\
`clang++-3.8 -std=c++14 libc++`\
`clang++-3.8 -std=c++11 libstdc++-v3`\
`clang++-3.8 -std=c++11 libc++`\
`clang++-3.7 -std=c++14 libstdc++-v3`\
`clang++-3.7 -std=c++14 libc++`\
`clang++-3.7 -std=c++11 libstdc++-v3`\
`clang++-3.7 -std=c++11 libc++`

They fail with the same ICE as before making the function non-friend
and declared outside `class uncomparable_string`.

The core dumps are different for `libstdc++-v3` compared to `libc++`,
but I haven't recorded these diffreences.

These configurations compile, but now generate a warning:

`clang++-3.6 -std=c++14 libstdc++-v3`\
`clang++-3.6 -std=c++14 libc++`\
`clang++-3.6 -std=c++11 libstdc++-v3`\
`clang++-3.6 -std=c++11 libc++`\
`clang++-3.5 -std=c++14 libstdc++-v3`\
`clang++-3.5 -std=c++14 libc++`\
`clang++-3.5 -std=c++11 libstdc++-v3`\
`clang++-3.5 -std=c++11 libc++`

The warning is

```text
test/compiling_tests.hpp:237:6:
warning: no previous prototype for function 'operator=='
[-Wmissing-prototypes]
bool operator==(const char*, const uncomparable_string&) = delete;
     ^
```

Compilers are from Compiler Explorer and have these versions

```bash
clang++-3.8 --version
clang version 3.8.1 (tags/RELEASE_381/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin

clang++-3.7 --version
clang version 3.7.1 (tags/RELEASE_371/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix

clang++-3.6 --version
clang version 3.6.2 (tags/RELEASE_362/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix

clang++-3.5 --version
clang version 3.5.2 (tags/RELEASE_352/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
```

I have been working on some code to further understand the issues,
but had an unfortunate data loss when my desktop 'melted down'
compiling `gcc` and `clang` simultaneously.

I hope to have more opportunity to investigate during this
holiday period.

**Comment by rollbear** [comment]
I'm sure a better solution can be found, and please experiment and see if you can find one. I thought I'd reached a solution that is good enough to help almost all users, without causing new harm to a few left out, so I reluctantly decided to go with that.

The older clang compilers do work in CE, but in the travis-ci builds they crassh :-(

After consultation, I see see that I also have a gcc bug report to file (the work-around should not be needed, all versions of gcc require it.)

**Comment by AndrewPaxie** [comment]
Curiously, adding `inline` to the function definition makes a difference:

```cpp
inline bool operator==(const char*, const uncomparable_string&) = delete;
```

This passes for all compilers except `clang++-3.8` and `clang++-3.7`.
No warnings are generated for `clang++-3.6` or `clang++-3.5`.

**Comment by rollbear** [comment]
Closing this now as fixed in v36, even though I'd like to see fixes for the older compilers too.
