### ISSUE TITLE
Working with c-style [] arrays or typedefs of them

### ISSUE THREAD

**Issue by jamespharvey20** [rollbear/trompeloeil#18]
Trying to mock out the unix <uuid.h>functions a library uses.  I've simplified the library out in this sample code.

It defines

```
typedef unsigned char uuid_t[16]
```

Question 1 - Is there any way to custom print such as `print(ostream&os, const uuid_t& uuid)`?  On a no match, it standard prints `uuid_t` as a `unsigned char*` since it decays into that, rather than using my custom printer which could print the 16 bytes as hex values.  It also assumes null-termination, which isn't the case here, so it reads past the uuid_t when printing (unless the next byte happens to be a 0.)  One thought I have is to allow a custom matcher to have an optional 4th argument, a lambda for a custom printer.  So perhaps `eq()` could never use a custom printer, but the user could write something like `eq_uuid()` which would both match and custom print?

```
  No match for call of uuid_unparse_upper with signature void(const uuid_t,
  char*) with.
    param  _1 == PO▒▒▒J1▒▒}▒ ▒▒;▒U▒    {{ [15] is the ';' rest is read past the uuid_t }}
    param  _2 ==

  Tried uuid.uuid_unparse_upper(eq(uuidBuffer), ne(nullptr)) at /home/mdarling
  /code/tests/libs/pcUUID/testPcUUID.cpp:73
    Expected  _1 == PO▒▒▒J1▒▒}▒ ▒▒;XoF   {{ [15] is the ';' rest is read past the uuid_t }}
```

Question 2 - Is there even any way to custom match `uuid_t`?  I'm running into `error: function returning an array`.

Question 3 - How can an argument be accepted no matter what?  I'm trying to have a `uuid_t` accepted no matter what, since it's an array and can't be nullptr, and as a variable its being written to instead of read, so any value is valid.  I've tried `any_matcher("uuid_t")` and `any_matcher<uuid_t>("uuid_t")` also with defining a `const char*` for `"uuid_t"` and using that, but I'm getting various gcc spew.

```
#include <catch.hpp>
#include <trompeloeil.hpp>
using namespace trompeloeil;

#include <string>
using namespace std;

#include <string.h> // bzero

constexpr unsigned int UUID_DASHED_STRING_LENGTH { 36 };

typedef unsigned char uuid_t[16]; // from /usr/include/uuid/uuid.h, outside my control

namespace trompeloeil {

   // Question 1 applies here - this never executes
   template <>
   void print(ostream& os, const uuid_t& uuid) {
      os << "Hello as const uuid_t&";
   }

   // Question 2 applies here - this doesn't compile
/*
   auto eq_uuid(const uuid_t& expected) {
      return make_matcher<uuid_t>(
         [](const uuid_t value, const uuid_t _expected) {
            return !memcmp(value, _expected, UUID_BINARY_LENGTH);
         },
         [](ostream& os, const uuid_t _expected) {
            os << "Hello from eq_uuid";
         },
         std::forward<const uuid_t>(expected)
      );
   }
*/

}

class mock_uuid {
   public:
      MAKE_MOCK1(uuid_generate, void(uuid_t));
      MAKE_MOCK2(uuid_unparse_upper, void(const uuid_t, char*));
};

TEST_CASE("") {
   mock_uuid uuid;

   uuid_t uuidBuffer { 0x50, 0x4f, 0xfd, 0x14, 0xd9, 0xc0, 0x4a, 0x31, 0xa5, 0xfa, 0x7d, 0x84, 0x20, 0xa3, 0x87, 0x3b };

   /* When calling uuid_generate, require it to set newUuid to uuidBuffer */

   // Question 3 applies here - would like to allow anything for arg0
   REQUIRE_CALL(uuid, uuid_generate(ne(nullptr)))
      .SIDE_EFFECT(memcpy(_1, uuidBuffer, sizeof(uuid_t)));

   uuid_t newUuid;
   bzero(newUuid, sizeof(uuid_t));
   uuid.uuid_generate(newUuid);

   REQUIRE(!memcmp(uuidBuffer, newUuid, sizeof(uuid_t)));

   /* And when calling uuid_unparse_upper, require it to set newParsedUuid to parsedUuid */

   string parsedUuid { "504FFD14-D9C0-4A31-A5FA-7D8420A3873B" };

   // Question 1 and 2 apply here:
   // Question 1 applies here - eq(uuidBuffer) compares as null-terminated unsigned char string, finding a no match
   //    due to a read-buffer-oveflow.  print(ostream&, const uuid_t&) never executes.
   // Question 2 applies here - eq_uuid(uuidBuffer) gives error: function returning an array
   REQUIRE_CALL(uuid, uuid_unparse_upper(eq(uuidBuffer), ne(nullptr)))
      .SIDE_EFFECT(memcpy(_2, parsedUuid.c_str(), UUID_DASHED_STRING_LENGTH));

   char* newParsedUuid = static_cast<char*>(malloc(UUID_DASHED_STRING_LENGTH));
   bzero(newParsedUuid, UUID_DASHED_STRING_LENGTH);
   uuid.uuid_unparse_upper(newUuid, newParsedUuid);

   REQUIRE(!strcmp(parsedUuid.c_str(), newParsedUuid));
}
```

**Comment by rollbear** [comment]
Ouch, that was a mean `typedef`.

From the back: To match anything, use [`trompeloeil::_`](https://github.com/rollbear/trompeloeil/blob/master/docs/reference.md#wildcard)

From a mocking point of view, I think you're better of representing `uuid_t` as a separate type.

```Cpp
class mock_uuid
{
  mock_api(uuid_t) ...
  uuid_t to_uuid_t() const ...
  frind std::ostream& operator<<(std::ostream&, const mock_uuid&) { ... } // formatting error messages
  ...
};
```

And then in your api-mock, use that type instead of the real one, although you obviously must be able to convert between them.

```Cpp
struct mock_api {
  MAKE_MOCK1(uuid_func, mock_uuid(mock_uuid));
};
```

That way your mock implementation of the API can be something like:

```Cpp
extern "C"
uuid_t uuid_func(uuid_t f)
{
  auto rv = mock_api::instance()->uuid_func(mock_uuid(f));
  return rv.to_uuid_t();
}
```

The above is a bit sketchy, and I haven't quite woken up yet, so see the above as something to improvise around.

**Comment by rollbear** [comment]
OK, I definitely wasn't quite awake, but here's a less sketchy code that actually works, at least for my example.

```Cpp
typedef unsigned char uuid_t[16];

class uuid_ref
{
public:
    uuid_ref(uuid_t& id) : uuid(id) {}
    bool operator==(const uuid_t& id) const {
        return memcmp(id, uuid, sizeof(uuid_t)) == 0;
    }
    void set(const uuid_t& id) {
        std::copy(std::begin(id), std::end(id), uuid);
    }
    friend
    std::ostream& operator<<(std::ostream& os, uuid_ref const& r)
    {
        for (size_t i = 0; i < sizeof(uuid_t); ++i)
        {
            os << std::hex << (unsigned)r.uuid[i] << ' ';
        }
    }
private:
    unsigned char* uuid;
};


struct mock_api
{
    MAKE_MOCK1(make, void(uuid_ref));
};

mock_api api;
extern "C"
void make_uuid(uuid_t& id)
{
    uuid_ref r(id);
    api.make(r);
}

int main()
{
    REQUIRE_CALL(api, make(trompeloeil::_))
//        .WITH(_1 == uuid_t{1,2,3,4,5,6,0,1,2,3,4,5,6,7,8,9})
        .SIDE_EFFECT(_1.set({1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1}));
    uuid_t uu;
    make_uuid(uu);
}
```

The idea is that the mock uses the `uuid_ref` to make it possible to print the values in a way that makes sense, and to get past the ugly consequences of the array `typedef`. Note that since `typedef` only creates an alias for a type, you really don't want to try to make an output stream operator for it, since it'd match all such arrays, regardless of alias name.

The silly `main()` function demonstrates matching with wildcard and commented line gives simple constraint example. You'd probably want a `uuid_cref` as well, to initialize with const uuid_t, and make them both equal comparable, that way you could use the `eq()` or `ne()` matchers instead of `WITH()`.

**Comment by jamespharvey20** [comment]
Thanks, perfect solution!
