### ISSUE TITLE
It's not clear to me how to handle reference parameters in expectations

### ISSUE THREAD

**Issue by RedDwarf69** [rollbear/trompeloeil#181]
I may have missed it, but I don't think the documentation is explicit about how reference parameters interact with expectations.

I may want to check that a mocked function receives as parameter reference X. I would not want to check the referenced value is equal to another one, I would be interested in verifying the memory address is the expected one... but I can't directly give it a pointer because the function takes a reference, not a pointer.

I can do `REQUIRE_CALL(my_mock, my_func(_)).WITH(&_1 == &obj_to_compare_to);`, but I am not 100% sure if I'm missing a simpler way.

**Comment by rollbear** [comment]
That's what I do. You may want to use `.LR_WITH()`, though, if `obj_to_compare_to` is a local  in the test function, otherwise you compare with the copy in the generated lambda.

**Comment by RedDwarf69** [comment]
> That's what I do.

Then unless somebody has some brilliant idea using a reference_wrapper or something to make it simpler/less verbose I guess this can be closed.

> You may want to use .LR_WITH(), though, if obj_to_compare_to is a local in the test function, otherwise you compare with the copy in the generated lambda.

Yeah, I changed the example and forgot to update that.
