### ISSUE TITLE
Latest git tag changed format from "v<NUM>" to just "<NUM>". Intentional?

### ISSUE THREAD

**Issue by bjornfor** [rollbear/trompeloeil#182]
I'd sleep a lot better at night if I knew whether this change in tag format was intentional :-)

**Comment by rollbear** [comment]
Grr. No. I can only blame it on having a fever that day and not quite having my head properly screwed on. Thanks for noticing. I've edited the github release name to `v37`, and also pushed a `v37` git tag (still keeping the old one.)

**Comment by bjornfor** [comment]
Thanks for the update (and fix)! Now I can sleep well tonight :-)
