### ISSUE TITLE
Runtime adapter for 'Status OK' reporting

### ISSUE THREAD

**Issue by moha-gh** [rollbear/trompeloeil#186]
We'd like to use the new "Status OK reporting" feature with Catch2 (really great addition, thanks!), but haven't found an easy way to enable it in our setup yet: We have a custom `main()` that calls `trompeloeil::set_reporter()`. As there is no equivalent to `set_reporter()` for the `sendOk()` override, we'd need to enable it in the tests itself - which, as they `#include <trompeloeil.hpp>` instead of `#include <catch2/trompeloeil.hpp>` , would apparently need modification to all of them (we also have no global test include file) :unamused: 

Would it be possible to add an `set_reporter(reporter_function, ok_reporter_function)` overload or similar? Given some pointers on how to implement this, I'd be happy to (try to) come up with a PR or help with testing.

**Comment by rollbear** [comment]
I think this should be relatively easy to do. If you look up `reporter<T>::sendOk`, you see that it currently does nothing. You can change it to behave similar to how `reporter<T>::send` (just above it) works, by obtaining and calling an ok_reporter object. For compatibility the ok_reporter object should default to doing nothing.

With that in place, I think it makes sense to either overload the `set_reporter` function with a two parameter version, that sets the ok_reporter also, or to change the signature of the `set_reporter` function such that it has a defaulted 2nd argument that is a default constructed `std::function<>`.

Do you think that's enough to get you going?

**Comment by moha-gh** [comment]
Yes, thanks. I'll give it a try in the next few days.
