### ISSUE TITLE
IMPLEMENT_MOCKx / IMPLEMENT_CONST_MOCKx doesn't seem to support 'noexcept'

### ISSUE THREAD

**Issue by RossiSoftLtd** [rollbear/trompeloeil#189]
Hi, 
I'm learning how to use this incredibly useful framework together with Catch2.

I've being trying to mock a simple interface with pure virtual methods declared with **noexcept** keyword, but it seems both the IMPLEMENT_MOCKx and IMPLEMENT_CONST_MOCKx are not supporting it?

I read your documentation and it seems that MAKE_MOCKx supports the **noexcept** keyword albeit I haven't use it as yet.

Am I doing something wrong or indeed the **noexcept** keyword is not intended to be used with pure virtual methods?

Many thanks in advance
Eddy

**Comment by rollbear** [comment]
I don't think it's possible, since the `noexcept`-ness would have to be discovered by the preprocessor.

You can do it with the somewhat more verbose `MAKE_MOCKn` and `MAKE_CONST_MOCKn` macros, but see the [FAQ](https://github.com/rollbear/trompeloeil/blob/master/docs/FAQ.md#mock_noexcept). It's complicated.

**Comment by RossiSoftLtd** [comment]
I see that it must be discover-able by the pre-processor, but I was more thinking about being able to specify the **noexcept** as an extra argument to the IMPLEMENT_MOCKx macro in the very same way it is possible on MAKE_MOCKx as you pointed out.

The reason why I ask is because I might have to mock an interface which I cannot remove the **noexcept** keyword from the definition in the first place and that extra argument would allow me to mock the virtual method accordingly.

Just a thought ;-)

Cheers
Eddy

**Comment by rollbear** [comment]
I believe i have a solution for you. Check out the branch `implement_mock_noexcept`. I have absolutely no idea how to automate a test for this. Please try it out, though. You just add an extra parameter to `IMPLEMENT_MOCKn(name, noexcept)`.

**Comment by rollbear** [comment]
Arghhh! Of course MSVC fails to compile it.

**Comment by RossiSoftLtd** [comment]
Hi, thank you very much for the patch. I can confirm it now works fine on **gcc (Debian 8.3.0-6) 8.3.0**, unfortunately I'm not able to test on MSVC, sorry ;-(

Thank you very much for making such wonderful framework.

Cheers
Eddy

**Comment by rollbear** [comment]
Persuading MSVC to cooperate was trickier than anticipated, but I've beaten it into submission. Care to check again that I haven't ruined your use case? I'll get on with updating the documentation before merging.

**Comment by RossiSoftLtd** [comment]
Hi, retested with new build and all is good ;-) Thank you!

Cheers
Eddy

**Comment by rollbear** [comment]
Included in release v38
