### ISSUE TITLE
Support Conan cmake_paths generator

### ISSUE THREAD

**Issue by kaibernhard** [rollbear/trompeloeil#192]
The current `conanfile.py` does not install the CMake package configuration files:

* `trompeloeil-config.cmake`
* `trompeloeil-config-version.cmake`
* `trompeloeil-targets.cmake`

This breaks the cmake_paths generator in Conan, which generates `cmake_paths.cmake` that can be used as `CMAKE_TOOLCHAIN_FILE` to non-intrusively (no Conan specific modifications in `CMakeLists.txt`) use `find_package (trompeloeil REQUIRED)`.

While looking into that, I also noticed a typo (`LICENCE` instead of `LICENSE`) in https://github.com/rollbear/trompeloeil/blob/4eba9aa8a9763b6b347b1de43b81aad77e04095c/conanfile.py#L23 which prevents the license to be included in the Conan package.

This patch installs the missing package config files and fixes the typo. It has a side effect of also including the docs in the Conan package. To address this, an option `TROMPELOEIL_INSTALL_DOCS` could be added in `CMakeLists.txt` and set to `OFF` in `conanfile.py`. I can prepare a PR with the patch and option for the docs.

```
diff --git a/conanfile.py b/conanfile.py
index efda93a..5d59d0f 100644
--- a/conanfile.py
+++ b/conanfile.py
@@ -11,7 +11,7 @@
 # Project home: https://github.com/rollbear/trompeloeil
 #
 
-from conans import ConanFile
+from conans import ConanFile, CMake
 
 
 class TrompeloelConan(ConanFile):
@@ -20,7 +20,7 @@ class TrompeloelConan(ConanFile):
     license = "Boost Software License - Version 1.0 - August 17th, 2003"
     url = "https://github.com/rollbear/trompeloeil.git"
     description = "Header only C++14 mocking framework"
-    exports_sources = "include/*", "LICENCE*.txt"
+    exports_sources = "include/*", "LICENSE*.txt", "CMakeLists.txt", "*.cmake", "docs/*"
     no_copy_source = True
     # No settings/options are necessary, this is header only
 
@@ -28,5 +28,7 @@ class TrompeloelConan(ConanFile):
         self.info.header_only()
 
     def package(self):
-        self.copy("include/*")
+        cmake = CMake(self)
+        cmake.configure(build_folder='build')
+        cmake.install()
         self.copy("LICENSE*.txt", dst="licenses")
```

**Comment by rollbear** [comment]
Ops. Thank you. Would you like to make a pull request for this, directly to master?
