### ISSUE TITLE
Clang latest generates `-Wsuggest-destructor-override` warnings

### ISSUE THREAD

**Issue by AndrewPaxie** [rollbear/trompeloeil#197]
Since commit 111167895d47558989f9f3a593a82527b016c7e7
was made to Clang on 12 July 2020, Trompeloeil has warnings
similar to the following being generated:

```text
./include/trompeloeil.hpp:1486:5:
warning: '~list' overrides a destructor but is not marked 'override'
[-Wsuggest-destructor-override]
```

This occurs since the project uses `-Weverything` on the command line
to generate new warnings as soon as possible.

Full list of destructors generating the warning
(line numbers are approximate, produced over multiple runs):

```text
1486:~list()
2721:~call_matcher_base()
2515:~deathwatched()
3162:~condition_base()
3211:~side_effect_base()
```

Compiles were on a version of source close to, but not quite, master.

Choices:

- Disable the warning on the Clang command line.
- Add `override` to the destructors where the warning is generated.
  In some cases the preceding `virtual` keyword is removed as the
  destructor is already virtual.

IMHO the second choice is the preferred choice.

**Comment by rollbear** [comment]
Good catch! Of course we should add the missing `override`s.

**Comment by AndrewPaxie** [comment]
I'll prepare a pull request.

**Comment by rollbear** [comment]
Included in v39
