### ISSUE TITLE
I can't understand the "Matches saturated call requirement" error message

### ISSUE THREAD

**Issue by RedDwarf69** [rollbear/trompeloeil#202]
I don't have a nice simple example to show, but in one of my tests I get this error:

```
[file/line unavailable]:0: FATAL ERROR: No match for call of functor with signature void(const device&) with.
  param  _1 == 16-byte object={
 0xd8 0x43 0x8f 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
 }

Matches saturated call requirement
  remove_device_callback.functor(trompeloeil::_) at example.cpp:240
```

Coming from a `TROMPELOEIL_REQUIRE_CALL(remove_device_callback, functor(trompeloeil::_));`

When the TROMPELOEIL_REQUIRE_CALL line is removed the error is the same, but without the `Matches saturated call requirement` thing.

So, `No match for call`... even if it `Matches`.
I would be saying "this is obviously a bug in trompeloeil". But it obviously knows about the match, it says `Matches saturated call requirement`... so maybe it is trying to tell me what the problem is. But I don't really understand its explanation. `saturated`? At the very least a FAQ entry could help here.

FWIW the function take a const reference to an interface type and it's receiving an implementation of that interface type.

**Comment by RedDwarf69** [comment]
I can now understand it. It means the method was called more times than expected. I would still say the error message/documentation can be made to make the fact more clear but, disclaimer: I'm not native.

**Comment by rollbear** [comment]
Man, sorry. Your understanding is correct, and I'm glad you figured it out, but I should of course have responded to you explaining this.

I'll add an entry to the FAQ. Thank you.

**Comment by rollbear** [comment]
Added a new entry to the FAQ. Please let me know if you think this would've solved it for you, or if something is still missing from the explanation.

**Comment by RedDwarf69** [comment]
Sorry, I didn't notice your replies until you closed it.
Yes, the FAQ would have made it clear to me (not sure I would have checked the FAQ :-p but hopefully Google will show it to people looking for it).
