### ISSUE TITLE
Unexpected behavior of ALLOW_CALL in sequence

### ISSUE THREAD

**Issue by PKua007** [rollbear/trompeloeil#204]
Hi!

I stumbled upon an unexpected behavior of `ALLOW_CALL` with two matching calls, but within a sequence. It is best replicated by a code:

```C++
class Test {
public:
    MAKE_MOCK1(set, void(int));
    MAKE_CONST_MOCK0(get, int());
};

TEST_CASE("trompeloeil test") {
    Test test;

    trompeloeil::sequence seq;
    REQUIRE_CALL(test, set(1))
        .SIDE_EFFECT(std::cout << "set(1)" << std::endl)
        .IN_SEQUENCE(seq);
    ALLOW_CALL(test, get())
        .IN_SEQUENCE(seq)
        .RETURN(1);
    REQUIRE_CALL(test, set(2))
        .SIDE_EFFECT(std::cout << "set(2)" << std::endl)
        .IN_SEQUENCE(seq);
    ALLOW_CALL(test, get())
        .IN_SEQUENCE(seq)
        .RETURN(2);

    test.set(1);
    std::cout << test.get() << std::endl;
    std::cout << test.get() << std::endl;
    test.set(2);
    std::cout << test.get() << std::endl;
}
```

I expect it to output

> set(1)
> get() = 1
> get() = 1
> set(2)
> get() = 2

however I get

> set(1)
> get() = 2
> get() = 2
> set(2)
> get() = 2

If I change `ALLOW_CALL` to `REQUIRE_CALL` and use `TIMES`, the output is correct. But I don't want a fixed number of `get()` invocations.

Is it the intended behavior, or a bug?

Cheers!

//edit
I found a workaround. Doing

```C++
REQUIRE_CALL(test, get())
        .IN_SEQUENCE(seq)
        .TIMES(AT_LEAST(1))
        .RETURN(1);
```

gives a correct behavior, however the problem will still be there if `get()` is allowed not be called at all, namely `AT_LEAST(0)`.

**Comment by PKua007** [comment]
One more comment to clarify: I am aware of fix "Fixed bug where ALLOW_CALL only worked with sequences
if called at least once" with v38, I am already using it and the problem persists. Before v38 the above code would yield sequence mismatch and wouldn't event print those incorrect values as I remember.

**Comment by rollbear** [comment]
Thanks. ALLOW_CALL *is* very problematic with sequences because it's very unclear when to go on to the next step in the sequence, and when it's OK to stay. After all, no call at all is also allowed. I'll have to think about this one.

**Comment by rollbear** [comment]
Yup, something is undeniably wrong here.

**Comment by rollbear** [comment]
OK, I now know why it's wrong (the bug was caused by trying to fix another problem with ALLOW_CALL with sequences.) Now I just have to figure out how to make it right without reintroducing the original bug.

**Comment by rollbear** [comment]
This was a very tricky one, but I believe it works now. Would you like to test branch [sequenced_allow_all](https://github.com/rollbear/trompeloeil/tree/sequenced_allow_call) and see if it holds for your cases? Violation reports can be improved and documentation needs to be updated, and probably a few more self-test test cases should be added to thoroughly ensure the functionality.

**Comment by PKua007** [comment]
Sure, I can test it directly in my more complicated "production" code, where I've actually found the bug.

**Comment by rollbear** [comment]
I notice that MSVC doesn't like this solution. Grr. A std::array<> of 0 size *is* well defined.

**Comment by rollbear** [comment]
Found a work-around. Green with all compilers now.

**Comment by rollbear** [comment]
Writing more tests revealed some remaining problems, so still not quite there with this one.

**Comment by rollbear** [comment]
New fixes with additional tests. Unfortunately travis-ci is having problems with github right now, so the build doesn't start. Appveyor has successfully completed all MSVC builds, though. If you feel daring, give it a shot again. Or wait until we get a green/red light from travis-ci.

**Comment by rollbear** [comment]
Green on all compilers now.

**Comment by rollbear** [comment]
Excellent! Thanks for verifying. I'll tag a release in the next few days.

**Comment by rollbear** [comment]
Included in release v39
