### ISSUE TITLE
How to mock polymorphic types?

### ISSUE THREAD

**Issue by rcdailey** [rollbear/trompeloeil#21]
I have an interface named "PaymentPlugin", and I derive several mock classes from it:

```
class TestPaymentPlugin1 : public PaymentPlugin
{
public:

   MAKE_CONST_MOCK0(Name, std::string(), override);
   MAKE_CONST_MOCK0(LastInputType, PaymentInputType(), override);
   MAKE_MOCK0(MakePayment, void(), override);
   MAKE_MOCK0(WaitForInput, void(), override);
};

class TestPaymentPlugin2 : public PaymentPlugin
{
public:

   MAKE_CONST_MOCK0(Name, std::string(), override);
   MAKE_CONST_MOCK0(LastInputType, PaymentInputType(), override);
   MAKE_MOCK0(MakePayment, void(), override);
   MAKE_MOCK0(WaitForInput, void(), override);
};
```

Elsewhere, I create these concrete mocked types and store them in a container:

```
   std::vector<std::unique_ptr<PaymentPlugin>> plugins;
   plugins.emplace_back(new TestPaymentPlugin1);
   auto& plugin1 = *plugins.back();
   plugins.emplace_back(new TestPaymentPlugin2);
   auto& plugin2 = *plugins.back();
```

I then require a function to be called:

```
   auto r1 = NAMED_REQUIRE_CALL(plugin1, WaitForInput());
   auto r2 = NAMED_REQUIRE_CALL(plugin2, WaitForInput());
```

However, MSVC compiler tells me:

> 'trompeloeil_tag_WaitForInput': is not a member of 'PaymentPlugin'

Does trompeloeil not support polymorphism? What is the appropriate way to verify that function calls occur through a virtual interface?

**Comment by rollbear** [comment]
The problem is that the *_CALL() macros need to operate on the static type, i.e. on the concrete mock type.

One way to solve your problem is to rephrase the tests like:

```Cpp
std::vector<std::unique_ptr<PaymentPlugin>> plugins;
auto plugin1 = new TestPaymentPlugin1;
plugins.emplace_back(plugin1);
auto plugin2 = new TestPaymentPlugin2;
plugins.emplace_back(plugin2);

auto r1 = NAMED_REQUIRE_CALL(*plugin1, WaitForInput());
auto r2 = NAMED_REQUIRE_CALL(*plugin2, WaitForInput());
```

**Comment by rcdailey** [comment]
Thanks; I suspected that but I wanted to be sure you didn't have some neat runtime utilities for this. I changed my code as follows:

```
   auto plugin1 = std::make_unique<TestPaymentPlugin1>();
   auto plugin2 = std::make_unique<TestPaymentPlugin2>();

   auto r1 = NAMED_REQUIRE_CALL(*plugin1, WaitForInput());
   auto r2 = NAMED_REQUIRE_CALL(*plugin2, WaitForInput());

   std::vector<std::unique_ptr<PaymentPlugin>> plugins;
   plugins.push_back(std::move(plugin1));
   plugins.push_back(std::move(plugin2));
   PaymentServiceHandler psh{std::move(plugins)};

   r1.reset();
   r2.reset();
```

**Comment by rollbear** [comment]
Which looks good. I assume the real code is a bit more involved, otherwise `r1` and `r2` are unnecessary, and you could just use `REQUIRE_CALL(...)` instead since they must be satisfied by the end of the local scope.

**Comment by rcdailey** [comment]
Well I plan to do more REQUIRE_CALL after construction, on the same object, but I don't want the previous expectations to be in effect. So you're right there is a bit more to this.
