### ISSUE TITLE
How to match double with precise?

### ISSUE THREAD

**Issue by spitfire2** [rollbear/trompeloeil#212]
I'd like to know how to match double with .2f precise on REQUIRE_CALL. I used eq(100.00) but it doesn't match my value 100.000000456.
Below is the match code.
`REQUIRE_CALL(observerMock, OnProfit(eq(100.00)));`

Thanks.

**Comment by rollbear** [comment]
Floating point numbers are hard to use correctly. If you're doing an equality comparison with floating point numbers you're almost certainly doing it wrong (except, maybe, if you compare with 0.0, but only maybe.)

This is not a Trompeloeil issue, but a floating point issue. You may want to check out this blog post.

https://randomascii.wordpress.com/2012/02/25/comparing-floating-point-numbers-2012-edition/

or if you really want to get into the gritty details

https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html
