### ISSUE TITLE
Move away from travis-ci

### ISSUE THREAD

**Issue by rollbear** [rollbear/trompeloeil#214]
5h40m to complete a run is totally unacceptable, and it's apparently not due to temporary problems, but rather a deliberate decision by travis-ci to give priority to paying customers (can't blame them, but not good for small open source projects like this.)

cirrus-ci, gitub-actions?

Relates o #102.

**Comment by arximboldi** [comment]
Sadly, if you pay for Travis, it is still super slow. I am very looking forward to migrate all my projects to something else. Probably Github Actions.

**Comment by offa** [comment]
I'm moving my projects to Github Actions, which is way faster and eg. supports custom container.

**Comment by rollbear** [comment]
Started a setup for github actions on branch `try_github_actions`. Thu functionality implemented seems to work line, but much is missing.

Remaining issues
==============
- [ ] Code coverage is not collected, and thus not forwarded to coveralls.io
- [ ] Ancient Linux compilers not supported (gcc < 6, clang < 5)
- [ ] No libc++ builds for clang++11
- [ ] libc++ fetch seems flaky. It seems different versions are located in different places.
- [ ] Apple/Clang builds
- [ ] MSVC builds

**Comment by offa** [comment]
> Ancient Linux compilers not supported (gcc < 6, clang < 5)

You can use docker images for that. I have migrated another project recently, using the `gcc` image (down to 4.9) and `teeks99/clang-ubuntu` (down to 4.0). Unfortunately clang <= 6 needs to build libc++ every time.

> No libc++ builds for clang++11

What's the problem with that version? I haven't experienced any issue with that version (using focal base image though).

**Comment by offa** [comment]
>       - name: Download Ninja and CMake

Why not stick with the cmake version, provided by the GH Actions images? It's up to date (3.19 at the moment).

Regarding ninja setup: I've used apt-get on linux, but there's a generic build step: https://github.com/seanmiddleditch/gha-setup-ninja

**Comment by rollbear** [comment]
Thanks @offa. Will try the docker images. This is work in progress, so the above aren't necessarily problems, just work that is not yet done. I do not foresee problems with Apple/MSVC buids, but I'm not there yet.

Libc++11. The script to download it, proudly stolen (and somewhat modified) from range-v3, fails because it sees clang++ 11.0.1, and there are only RC-images lib libc++ 11.0.1.

**Comment by offa** [comment]
Maybe you can get some ideas from here: https://github.com/Dobiasd/FunctionalPlus/blob/master/.github/workflows/ci.yml

**Comment by AndrewPaxie** [comment]
Excited to see this work underway.  I'm once more in follow-along mode however.

**Comment by rollbear** [comment]
Coming along nicely. Much less cluttered script now, and covers almost all that is needed. 12 minutes for the full matrix is impressive, but it will (probably) take longer when functionality is added. Still missing  a few old clang:s, but those have never caused any problems, so it's not a big deal. Building for more versions of MSVC is a must, since that compiler family has caused so much pain historically.

Remaining todo:

- [ ] Older MSVCs.
- [ ] coverage still missing
- [ ] build optimizing and matrix cleanup (too repetitive). Lexy looks like an interesting source of inspiration with its use of docker images. https://github.com/foonathan/lexy/blob/main/.github/workflows/feature_ci.yml
- [ ] Flaky libc++ access. Probably fixed by containers too

**Comment by rollbear** [comment]
Getting there now. coverage collection works, but uploading to coveralls does not. There's an issue for `kcov` that explains how to do it, though, so it should probably not be long.

https://github.com/SimonKagstrom/kcov/issues/346

**Comment by rollbear** [comment]
Finally done. Moved coverage to codecov.io which offered less resistance than coveralls.io. Shiny new badges on the READE too!
