### ISSUE TITLE
ALLOW_CALL for functions returning non-movable objects (e.g. std::unique_ptr)

### ISSUE THREAD

**Issue by svengit** [rollbear/trompeloeil#217]
Maybe I am missing something, but I can't find any examples and can't get it to work.

**Comment by rollbear** [comment]
Can you show a code snipped you want to work?

**Comment by svengit** [comment]
I hope this captures the essence of what I try to test

`#include <memory>
#include <string>

#include "catch2/catch.hpp"
#include "catch2/trompeloeil.hpp"

struct ComplexClass
{
    ComplexClass(int f1, std::string_view f2)
    {
        field1 = f1;
        field2 = std::string{f2};
    }
    int field1;
    std::string field2;
};

class MockMeInterface
{
public:
    virtual std::unique_ptr<ComplexClass> getComplexClass() = 0;
};

class MockMe : public MockMeInterface
{
public:
    std::unique_ptr<ComplexClass> getComplexClass() override
    {
        return std::make_unique<ComplexClass>(42, "foobar");
    }
};

class Mocker : public trompeloeil::mock_interface<MockMeInterface>
{
public:
    MAKE_MOCK0(getComplexClass, std::unique_ptr<ComplexClass>());
};

TEST_CASE("SSCCEE")
{
    using trompeloeil::_;

    auto mock = std::make_shared<Mocker>();

    SECTION("Check calls")
    {
        ALLOW_CALL(*mock, getComplexClass()).RETURN(trompeloeil::ne(nullptr));

        // Do complex stuff with some totally different object X that leads to a call of getComplexClass() inside that object
    }
}`

**Comment by rollbear** [comment]
So there is clearly some confusion here. I'm not sure what it is you want to do.

However, `.RETURN()` is for an expression that results in the value returned from the call. For example:

```Cpp
        ALLOW_CALL(*mock, getComplexClass()).RETURN(std::make_unique<ComplexClass>(42, "foobar"));
```

See: https://github.com/rollbear/trompeloeil/blob/master/docs/CookBook.md#return_values

The matcher `tromeloei::ne(nullptr)` is not meaningful as a return value. Matchers are used for parameters in expectations, to select which parameter values are allowed to match.

See https://github.com/rollbear/trompeloeil/blob/master/docs/CookBook.md#-matching-values-with-conditions

In your example you have a class `MockMe` that is not used at all. What's the intended purpose of it?

**Comment by svengit** [comment]
Thanks for your reply.

I just added the MockMe class to be more clear about what the "normal" interface implementation would look like.

I tried to use the `trompeloeil::ne(nullptr)` matcher in a desperate attempt to get it to compile.

I tried several approaches today and none of them compiled. The closest attempt to what you posted fails because one of the arguments of `ComplexClass`'s ctor (a boost::asio::io_context) is non copyable:

```
trompeloeil.hpp:4690:17: error: use of deleted function ‘boost::asio::io_context::io_context(const boost::asio::io_context&)’
 4690 |   handle_return([capture](auto& trompeloeil_x) -> decltype(auto) {             \
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 4691 |     auto& _1 = ::trompeloeil::mkarg<1>(trompeloeil_x);                         \
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 4692 |     auto& _2 = ::trompeloeil::mkarg<2>(trompeloeil_x);                         \
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 4693 |     auto& _3 = ::trompeloeil::mkarg<3>(trompeloeil_x);                         \
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 4694 |     auto& _4 = ::trompeloeil::mkarg<4>(trompeloeil_x);                         \
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 4695 |     auto& _5 = ::trompeloeil::mkarg<5>(trompeloeil_x);                         \
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 4696 |     auto& _6 = ::trompeloeil::mkarg<6>(trompeloeil_x);                         \
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 4697 |     auto& _7 = ::trompeloeil::mkarg<7>(trompeloeil_x);                         \
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 4698 |     auto& _8 = ::trompeloeil::mkarg<8>(trompeloeil_x);                         \
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 4699 |     auto& _9 = ::trompeloeil::mkarg<9>(trompeloeil_x);                         \
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 4700 |     auto&_10 = ::trompeloeil::mkarg<10>(trompeloeil_x);                        \
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 4701 |     auto&_11 = ::trompeloeil::mkarg<11>(trompeloeil_x);                        \
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 4702 |     auto&_12 = ::trompeloeil::mkarg<12>(trompeloeil_x);                        \
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 4703 |     auto&_13 = ::trompeloeil::mkarg<13>(trompeloeil_x);                        \
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 4704 |     auto&_14 = ::trompeloeil::mkarg<14>(trompeloeil_x);                        \
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 4705 |     auto&_15 = ::trompeloeil::mkarg<15>(trompeloeil_x);                        \
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 4706 |     ::trompeloeil::ignore(_1,_2,_3,_4,_5,_6,_7,_8,_9,_10,_11,_12,_13,_14,_15); \
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 4707 |     return ::trompeloeil::decay_return_type(__VA_ARGS__);                      \
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 4708 |   })
      |   ~              
```

What I'd need is a matcher for 'return anything that is a pointer of this type', which I thought  `trompeloeil::ne(nullptr)` would do for me (I also tried something like `std::unique_ptr<ComplexClass> retPtr; .... RETURN(retPtr)`)

**Comment by rollbear** [comment]
I take it that your actual problem is something completely different, though I'm not sure what.

Here's a rewrite of your example, as I've understood it (or misunderstood it), which compiles fine. I've taken the liberty of dropping "catch2", just to remove one dependency and ensure that the problem is not related to Catch.

https://godbolt.org/z/vo786r

The compilation error you quote tells me your expectation wants to copy a Boost ASIO `io_context`, which is non-copyable, and this copy has to do with the lambda capture on is unrelated to the return. So, am I right in guessing that the actual return expression you want uses an `io_context`? Have you tried using `.LR_RETURN(...)` instead, to access the `io_context` by reference rather than copying it?

**Comment by svengit** [comment]
Yep, I guess that's the case. The actual call of `std::make_unique<>()` gets a shared pointer of the caller via shared_from_this(), an io_context and a piece of data, let's say a string.

I actually tried `LR_RETURN()`, but probably not with the right arguments.

So here is kind of what I want (hopefully): https://godbolt.org/z/cv5eWW

**Comment by rollbear** [comment]
Here are two ways to make your example compile. Hopefully the comments will explain why they are written the way they are.

https://godbolt.org/z/qEn37q

**Comment by svengit** [comment]
Thanks. 
I think I had that before and it compiles but the tests don't work (at least in my case). Probably because the Mock doesn't provide the same  IOContext (?).

Thanks  for your help and effort. I think I'll disable the tests until I either change the class structure or think of a better way to test these classes

**Comment by rollbear** [comment]
Since the IOContext is not copyable, the mock must either return the same or create a new one, and it should be obvious from how you write the test code which case it is. One possible problem is that in Alt1 (in my example) it returns the referenced `unique_ptr<>` by moving from it, so `ret` is `nullptr` after the first matching call. If your tested code calls the mock several times (which it may do, since it's `ALLOW_CALL`), only the first call would see the intended object, the remaining ones would get `nullptr`.

**Comment by svengit** [comment]
Ok, I don't think I can write those tests right now. I'd either need to just ignore the return value in this case or restructure my whole class structure. Thanks for your help!
