### ISSUE TITLE
Add documentation for the C++11 interface

### ISSUE THREAD

**Issue by aTom3333** [rollbear/trompeloeil#219]
The documentation is lacking information regarding the interface when using the C++11 standard (at least I couldn't find any).

I managed to find the information I was looking for by reading through this [https://github.com/rollbear/trompeloeil/issues/1](thread) (that is, the fact that I need to use `REQUIRE_CALL_V` instead of `REQUIRE_CALL` and the difference in usage). 
But some sections dedicated about this subject (and more regarding the C++11 interface) in the documentation would be appreciated.

I don't think I can contribute myself as I don't know the library very much, for now I only have a basic usage of it.

**Comment by rollbear** [comment]
You did not find what you needed here, or you did not find this link (it's available from the top level README, under "compiler compatibility".)

https://github.com/rollbear/trompeloeil/blob/master/docs/Backward.md

**Comment by aTom3333** [comment]
Oh, guess I'm bad at looking... Thanks for the link, this is exactly what I was looking for

**Comment by AndrewPaxie** [comment]
@aTom3333 : You might also find this video of my backporting experience helpful,
https://youtu.be/KKvSVyZ4_5k
