### ISSUE TITLE
Side-effect that calls another member function?

### ISSUE THREAD

**Issue by rcdailey** [rollbear/trompeloeil#22]
I'm mocking a class called "PaymentPlugin":

```
class TestPaymentPlugin1 : public PaymentPlugin
{
public:

   MAKE_CONST_MOCK0(Name, std::string(), override);
   MAKE_CONST_MOCK0(LastInputType, PaymentInputType(), override);
   MAKE_MOCK0(MakePayment, void(), override);
   MAKE_MOCK0(WaitForInput, void(), override);
   MAKE_MOCK0(Deactivate, void(), override);
};

class TestPaymentPlugin2 : public PaymentPlugin
{
public:

   MAKE_CONST_MOCK0(Name, std::string(), override);
   MAKE_CONST_MOCK0(LastInputType, PaymentInputType(), override);
   MAKE_MOCK0(MakePayment, void(), override);
   MAKE_MOCK0(WaitForInput, void(), override);
   MAKE_MOCK0(Deactivate, void(), override);
};
```

Unit test code:

```
   auto plugin1 = new TestPaymentPlugin1;
   auto plugin2 = new TestPaymentPlugin2;

   ALLOW_CALL(*plugin1, Name())
      .RETURN("plugin1");

   ALLOW_CALL(*plugin2, Name())
      .RETURN("plugin2");

   REQUIRE_CALL(*plugin1, WaitForInput())
      .TIMES(1);

   REQUIRE_CALL(*plugin2, WaitForInput())
      .TIMES(1);

   REQUIRE_CALL(*plugin1, Deactivate())
      .TIMES(1)
      .SIDE_EFFECT(plugin1->SendCompletion(true));

   REQUIRE_CALL(*plugin2, Deactivate())
      .TIMES(1);

   std::vector<std::unique_ptr<PaymentPlugin>> plugins;
   plugins.emplace_back(plugin1);
   plugins.emplace_back(plugin2);
   PaymentServiceHandler psh{std::move(plugins)};

   ArgumentParser args;
   args["command"] = ttm::lexical_cast<std::string>(PaymentServiceCommand::StartSession);
   psh.HandleServiceRequest(Services::ServiceRequestContext{nullptr, args, true});
```

The normal behavior of a plugin is as follows:

1. `HandleServiceRequest()` calls the overridden `PaymentPlugin::WaitForInput()` on both instances.
2. The implementation of `TestPaymentPlugin1::WaitForInput()` for the `plugin1` instance invokes a non-virtual base function called `PaymentPlugin::SendCompletion(bool)`.
3. The implementation of that `SendCompletion()` function sends an event, which `PaymentServiceHandler` receives, and subsequently calls `TestPaymentPlugin2::Deactivate()`.

When I run this test, it informs me that `Deactivate()` was not called. Upon further debugging, the side effect is never actually executed (or at least, I never get a call to `SendCompletion()` in the base class). Is there a way to make this work? So much of what a payment plugin concrete type does is implementation detail, that I can't reliably work with that outside of the class in my test fixtures. So I need my mock implementations to assume some responsibility for the logic. Another ideal solution would be the ability to provide an implementation to the mocked functions of `TestPaymentPlugin1`, but I don't see a way to do this.

**Comment by rollbear** [comment]
Number 2 in your list surprises me, but maybe I misunderstand. You say the implementation of `TestPaymentPlugin1::WaitForInput()` calls `SendCompletion()`, but `TestMaymentPlugin1` has a mocked `WaitForInput()` which you say should do nothing (with the `ALLOW_CALL()s`. What am I getting wrong?

What you can do is to use a tracer to follow what happens.

Somewhere in your test, add:

```Cpp
  trompeloeil::stream_tracer trace_obj{std::cout}; // or other stream
```

The tracer object will show on `std::cout` (in the above example) which matching expectations are activated and with what parameters. Unfortunately it doesn't show return values (working on that) but that does not seem to be a big issue in your example above.

BTW, all the `.TIMES(1)` on `REQUIRE_CALL()` are unnecessary. Exactly once is the default for `REQUIRE_CALL()`.

**Comment by rcdailey** [comment]
Sorry, my code was completely wrong. I actually have it working now:

```
      REQUIRE_CALL(*plugin1, WaitForInput())
         .SIDE_EFFECT(plugin1->SendCompletion(true));

      REQUIRE_CALL(*plugin2, WaitForInput());
      REQUIRE_CALL(*plugin2, Deactivate());
```

What I *really* wanted confirmation of is how you intended on mocked member functions calling other member functions of the same instance of the mock class itself. Based on your last response, you didn't red-flag it, so it seems correct then?

**Comment by rollbear** [comment]
Calling another function on the same mock object is perfectly OK. Although, I realise that it doesn't work at all if you end up recursively calling the same function again (on the same instance.) I had really not thought about that situation at all. That's worth a separate issue, though.

**Comment by rcdailey** [comment]
Thanks for your feedback. Might I recommend a entry in your cookbook on this specific use case for side effects (that is: calling member functions)?

**Comment by rollbear** [comment]
Just an update for the fun of it. It turns out I was wrong about an expectation recursively calling the same mocked function. I added what I intended to be a failing test case, and it worked. I'd like to clean the code up a bit, though. The test case is added to the tail end of the `compiling_tests.cpp` program on branch develop, if you're curious, so from now on I intend to ensure that it continues to always work.

**Comment by rcdailey** [comment]
Sorry to bump a super old issue, but I do run into this every now and then. The work around I've found for the recursive case at the moment is this (note my example is different this time around):

```cpp
// Mock class
class MockController : public Controller
{
public:
   MAKE_MOCK1(RequestLease, std::shared_ptr<Lease>(AdUnitRequestInfo), override);
};

// Later in my TEST_CASE:
ALLOW_CALL(mock_controller, RequestLease(_))
   .LR_RETURN(mock_controller.Controller::RequestLease(_1));
```

This allows me to make sure that `RequestLease()` is invoked through Trompeloeil, but additionally define its behavior to use the base-class implementation, just as if I hadn't used the mock version of `Controller` in the first place.

Honestly I'd prefer if `.RETURN(Controller::RequestLease(_1));` worked, but it doesn't, I assume because internally the `RETURN` macro does not place its code directly in a function owned by the mock class. So the compiler thinks its trying to call a static function, instead of the base override for a non-static member function.

**Comment by rollbear** [comment]
Yeah, that would be neat, but I don't think it's possible. As you so correctly assume, the code in the `LR_RETURN` macro expansion lives in a lambda in the scope of your test code, and not in the class. However, you may want to take a peek into issue #70 where an alternative approach is discussed.
