### ISSUE TITLE
Conan center marks Trompeloeil as legacy package

### ISSUE THREAD

**Issue by offa** [rollbear/trompeloeil#220]
The [latest Trompeloeil package](https://conan.io/center/trompeloeil) at conan center is marked as legecy package:

> Depreciation Notice: LEGACY PACKAGE
> This package may no longer be supported.

Unfortunately there's no information why.

**Comment by rollbear** [comment]
Hrmm. It proabably has something to do with the new mechanism to add packages to conan-center, that I have not bothered with because the old one still worked. I'll look into it. Thanks for reporting.

**Comment by blackliner** [comment]
https://github.com/conan-io/conan-center-index/pull/3901

**Comment by offa** [comment]
The new package is available, thanks @blackliner !
