### ISSUE TITLE
Return Errors

### ISSUE THREAD

**Issue by scwong781** [rollbear/trompeloeil#231]
I just recently started using the mocking abilities with the Catch2 unit testing and I've been constantly getting the same errors whenever I try to use RETURN or LR_RETURN. The errors are as follows:

- ‘class std::unique_ptr<trompeloeil::expectation>’ has no member named ‘handle_return’
- ‘trompeloeil_e_t’ has not been declared
- no matching function for call to ‘mkarg(int&)’
- incomplete type ‘std::tuple_size<int>’ used in nested name specifier

To preface this, all I've done with my program so far is copying and pasting the Trompeloeil.hpp and the catch2/trompeloeil.hpp files into my code and then mocking the interface I wanted, so if there are any further initial implementation steps that I'm missing, please let me know.

**Comment by rollbear** [comment]
Can you please provide a (small) example? As you may have noticed, the self-test program is written using catch2, and (of course) uses all functionality there is. Also, what compiler, version, operating system and compilation flags?

**Comment by rollbear** [comment]
Ouch, gcc-4.8. Crikey! Feel like looking into this @AndrewPaxie ?

BTW, you haven't showed anything at all about the type "Mock". What does it look like?

**Comment by scwong781** [comment]
Mock is the mocking from a concrete class, if that's the type you are interested in. I pretty much just used the MAKE_MOCKn instruction on all of the functions (there are only public ones). I've ran a test with a void return function and that worked perfectly, it's just any test with RETURN in it.

**Comment by rollbear** [comment]
OK, so, to begin with there is no *Trompeloeil* macro `TROMPELOEIL_ALLOW_CALL_F`. I presume you mean `TROMPELOEIL_ALLOW_CALL_V`, but the syntax for its invocation is wrong. See https://github.com/rollbear/trompeloeil/blob/master/docs/Backward.md#cxx11_allow_call

Here's a link to a working version, assuming my guess about how the type `Mock` is written is correct.

https://godbolt.org/z/3744xbxfo

**Comment by AndrewPaxie** [comment]
I think @rollbear has pointed out the right direction. I hope you are using v40 (latest release) of trompeloeil.

**Comment by scwong781** [comment]
Thank you so much, this fixed everything!

**Comment by scwong781** [comment]
I'm so sorry, but I'm getting another error that I can't figure out. It's saying that I have "No match for call of Initialize with signature int() with.". I've tried to stop debug using stops to find the root of the problem, but it's not leading anywhere. I'm still using the same code as before.

**Comment by rollbear** [comment]
Show a complete full program that exhibits this behaviour, otherwise you leave me guessing.

**Comment by scwong781** [comment]
I'm sorry for leaving this open. The error ended up being an user error as when I copied the trompeloeil.hpp file, it added spaces and lines that weren't originally included, thus messing up the library and resulting in the errors.
