### ISSUE TITLE
Clang latest generates `-Wreserved-identifier` warnings

### ISSUE THREAD

**Issue by AndrewPaxie** [rollbear/trompeloeil#236]
Since commit `b83b23275b745287bf9d3d72a93b593119f53f75` was merged
into Clang latest around 3 May 2021, Trompeloeil has warnings
similar to the following being generated:

```text
In file included from test/compiling_tests.hpp:27:
./include/trompeloeil.hpp:444:12:
warning: identifier '_Unique_if' is reserved because
it starts with '_' followed by a capital letter
[-Wreserved-identifier]
    struct _Unique_if
           ^
```

Similar warnings are generated for the following identifiers:

```text
_Single_object
_Unknown_bound
_Known_bound
```

Occurs only when compiling in `-std=c++11` mode,
since the affected code is otherwise omitted
from the translation unit.

Suggested workaround: Make the identifiers snake case:

```text
_Unique_if       -> unique_if
_Single_object   -> single_object
_Unknown_bound   -> unknown_bound
_Known_bound     -> known_bound
```

For a different implementation of similar facilities, see
<https://github.com/abseil/abseil-cpp/blob/master/absl/memory/memory.h>

**Comment by rollbear** [comment]
Sloppy of me. I should've caught this. But it 's easy to fix, thankfully.

**Comment by AndrewPaxie** [comment]
The errors were all mine.  I should have thought harder before blinding implementing code from a standards proposal.

The change is in progress.

**Comment by rollbear** [comment]
Included in tag v41
