### ISSUE TITLE
Disable `-Wreserved-identifier` warning in build of tests

### ISSUE THREAD

**Issue by AndrewPaxie** [rollbear/trompeloeil#237]
Catch2 generates many `-Wreserved-identifier` warnings when
compiling with Clang latest after 3 May 2021.

See: <https://github.com/catchorg/Catch2/issues/578>

Disable this warning in Trompeloeil builds with Clang
if it is a supported warning.

**Comment by rollbear** [comment]
This one's done after merge of #239
