### ISSUE TITLE
FindThreads (and Threads::Threads) should be preferred over explicit pthread linkage

### ISSUE THREAD

**Issue by horenmar** [rollbear/trompeloeil#248]
Currently when a target requires threads, the project's CMakeLists checks if it is being used for MSVC and if not, adds `pthread` to target's linked libraries, [like here](https://github.com/rollbear/trompeloeil/blob/8316f4d45cd6e7de9a5f654bda58028aa04a7881/CMakeLists.txt#L277-L288).

This is needlessly verbose compared to using CMake's support for threads via [`FindThreads`](https://cmake.org/cmake/help/latest/module/FindThreads.html), which could be used to rewrite the linked code to something like this:

```cmake
  find_package(Threads REQUIRED)
  target_link_libraries(
    thread_terror
    PUBLIC
      trompeloeil
      Threads::Threads
  )
```

**Comment by rollbear** [comment]
I did not know this. TIL. Thank you.

**Comment by AndrewPaxie** [comment]
Thank you.

**Comment by rollbear** [comment]
Fix included in release v42
