### ISSUE TITLE
-Wgnu-zero-variadic-macro-arguments warnings witch clang msvc

### ISSUE THREAD

**Issue by u3shit** [rollbear/trompeloeil#250]
When compiling to windows with clang in msvc compatibility mode, it defines both `__clang__` and `_MSC_VER`. At the beginning of trompleloleil.hpp, it correctly checks for `#if defined(__clang__)`, but later at https://github.com/rollbear/trompeloeil/blob/2b268316f5ae743938e36fc20e6c82ac13b830d0/include/trompeloeil.hpp#L167 it uses `_MSC_VER` to determine which `TROMPLEOEIL_CONCAT` macro to use. Unfortunately, the MSVC version macro requires at least 3 parameters, but it's usually called with only two, resulting in a lot of warnings at each usage of `MAKE_MOCK*`.

**Comment by rollbear** [comment]
I must be misunderstanding something, because the warning and the source line together don't make any sense at all. The preprocessor statement on line 167 just tests if there is such a macro defined. It does not attempt to expand it, so it should not matter the slightest how many arguments it expects.

Can you please show the actual compilation error message?

**Comment by u3shit** [comment]
No, sorry, I get the warning when anything tries to use the concat macro, not when it is defined. I get at least a dozen warning for every MAKE_MOCK, like this:
```
../../src/wot/ui/terminal/widget_mock.hpp:31:5: warning: must specify at least one argument for '...' parameter of variadic macro [-Wgnu-zero-variadic-macro-arguments]
    MAKE_MOCK2(GetFlowBlock, FlowBlock(std::uint32_t, Size), override);
    ^
/home/u3/nepu/wot/ext/mocks/include/trompeloeil.hpp:5216:35: note: expanded from macro 'MAKE_MOCK2'
#define MAKE_MOCK2                TROMPELOEIL_MAKE_MOCK2
                                  ^
/home/u3/nepu/wot/ext/mocks/include/trompeloeil.hpp:4437:3: note: expanded from macro 'TROMPELOEIL_MAKE_MOCK2'
  TROMPELOEIL_MAKE_MOCK_(name,,2, sig, __VA_ARGS__,,)
  ^
/home/u3/nepu/wot/ext/mocks/include/trompeloeil.hpp:4727:29: note: expanded from macro 'TROMPELOEIL_MAKE_MOCK_'
  trompeloeil_self_ ## name(TROMPELOEIL_PARAM_LIST(num, sig)) constness        \
                            ^
/home/u3/nepu/wot/ext/mocks/include/trompeloeil.hpp:313:6: note: expanded from macro 'TROMPELOEIL_PARAM_LIST'
    (TROMPELOEIL_REMOVE_PAREN(func_type))
     ^
/home/u3/nepu/wot/ext/mocks/include/trompeloeil.hpp:193:39: note: expanded from macro 'TROMPELOEIL_REMOVE_PAREN'
#define TROMPELOEIL_REMOVE_PAREN(...) TROMPELOEIL_CONCAT(TROMPELOEIL_CLEAR_,   \
                                      ^
/home/u3/nepu/wot/ext/mocks/include/trompeloeil.hpp:170:70: note: expanded from macro 'TROMPELOEIL_CONCAT'
#define TROMPELOEIL_CONCAT(x, ...) TROMPELOEIL_CONCAT_(x, __VA_ARGS__)
                                                                     ^
/home/u3/nepu/wot/ext/mocks/include/trompeloeil.hpp:169:9: note: macro 'TROMPELOEIL_CONCAT_' defined here
#define TROMPELOEIL_CONCAT_(x, y, ...) x ## y __VA_ARGS__
        ^
```

Or when I use `IN_SEQUENCE`:
```
../../src/wot/ui/terminal/flow_layout.cpp:184:43: warning: must specify at least one argument for '...' parameter of variadic macro [-Wgnu-zero-variadic-macro-arguments]
    REQUIRE_CALL(*b, GetFlowBlock(7, 32)).IN_SEQUENCE(s).RETURN(
                                          ^
/home/u3/nepu/wot/ext/mocks/include/trompeloeil.hpp:5310:35: note: expanded from macro 'IN_SEQUENCE'
#define IN_SEQUENCE               TROMPELOEIL_IN_SEQUENCE
                                  ^
/home/u3/nepu/wot/ext/mocks/include/trompeloeil.hpp:5183:15: note: expanded from macro 'TROMPELOEIL_IN_SEQUENCE'
  in_sequence(TROMPELOEIL_INIT_WITH_STR(::trompeloeil::sequence_matcher::init_type, __VA_ARGS__))
              ^
/home/u3/nepu/wot/ext/mocks/include/trompeloeil.hpp:247:3: note: expanded from macro 'TROMPELOEIL_INIT_WITH_STR'
  TROMPELOEIL_CONCAT(TROMPELOEIL_INIT_WITH_STR,                                \
  ^
/home/u3/nepu/wot/ext/mocks/include/trompeloeil.hpp:170:70: note: expanded from macro 'TROMPELOEIL_CONCAT'
#define TROMPELOEIL_CONCAT(x, ...) TROMPELOEIL_CONCAT_(x, __VA_ARGS__)
                                                                     ^
/home/u3/nepu/wot/ext/mocks/include/trompeloeil.hpp:169:9: note: macro 'TROMPELOEIL_CONCAT_' defined here
#define TROMPELOEIL_CONCAT_(x, y, ...) x ## y __VA_ARGS__
        ^
```
I actually get 794 warnings from a simple file.
It looks like replacing `#if defined(_MSC_VER)` with `#if TROMPELOEIL_MSVC` makes warning go away, as in that case clang will use the second version of the concat macro.

**Comment by rollbear** [comment]
Ah, OK, thanks! I'll get back to you. If you want to, you can write a pull request with that change, and I'll gladly accept it.

**Comment by u3shit** [comment]
I would create a PR if microsoft would allow me to push to github, but this is what I had in mind:
https://git.neptards.moe/u3shit/trompeloeil/commit/45a25d5c9151215ecd7bcf21e94b01a7c1bfe364
I replaced the two ifdefs guarding the macro definitions with `TROMPELOEIL_MSVC`, as clang doesn't need those workarounds. I'm not sure whether the `is_equalcomparable` is beacuse a compiler or a standard library problem, so I left that alone. Also note that https://github.com/rollbear/trompeloeil/blob/2b268316f5ae743938e36fc20e6c82ac13b830d0/include/trompeloeil.hpp#L35-L37 can be incorrect sometimes, since clang's c++ support != MSVC's c++ support (and clang can define `_MSC_VER` to pretty much anything, see `-fms-compatibility-version`. Plus if you use libc++ instead of microsoft's STL, even the standard library is different). To be honest this is clang-msvc is a frankeinstein monster, and as long as it appears to work, I'm happy.

**Comment by rollbear** [comment]
Thanks. I have a branch `clang_msvc_warnings`, with your fix above. It passes all other CI, but could you please test the branch to see that I didn't mess up your work? I don't have access to that environment, unfortunately, so I'm working blind here.

**Comment by u3shit** [comment]
Thanks, it's working fine for me.

**Comment by rollbear** [comment]
Excellent. Merged to main. Keeping the issue open until a release is tagged.

**Comment by rollbear** [comment]
Fix included in release v42
