### ISSUE TITLE
`std::byte` value less than `0x10` in expectation isn't printed correctly in failure message

### ISSUE THREAD

**Issue by studoot** [rollbear/trompeloeil#255]
Consider the following code:

```c++
 #define CATCH_CONFIG_MAIN
 #include <catch.hpp>
 #include <catch2/trompeloeil.hpp>

 using trompeloeil::eq;

 struct A {
   virtual ~A() = default;
   virtual void blah(std::byte b) const = 0;
 };

 struct mock_A : public A {
   ~mock_A() override = default;
   MAKE_CONST_MOCK1(blah, void(std::byte), override);
 };

 TEST_CASE("x", "[x]") {
   mock_A a;
   REQUIRE_CALL(a, blah(std::byte{3}));
   REQUIRE(false);
 }
```

This should (and does) fail, as the mocked method is never called. However, the diagnostic printed by Trompeloeil displays the expected parameter value as `0x30` rather than `0x03`:

```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
a is a Catch v2.13.7 host application.
Run with -? for options

-------------------------------------------------------------------------------
x
-------------------------------------------------------------------------------
a.cpp:17
...............................................................................

a.cpp:20: FAILED:
  REQUIRE( false )

./catch2/trompeloeil.hpp:53: FAILED:
  CHECK( failure.empty() )
with expansion:
  false
with message:
  failure := "a.cpp:19
  Unfulfilled expectation:
  Expected a.blah(std::byte{3}) to be called once, actually never called
    param  _1 == 1-byte object={ 0x30 }
  "

===============================================================================
test cases: 1 | 1 failed
assertions: 2 | 2 failed
```

The code was compiled using g++-10 on Ubuntu 18.04, using the latest versions of Catch2 (v2.13.7) and Trompeloeil (v41), with the following command-line:

```
g++-10 --std=c++17 a.cpp -o a
```

From some experimentation, it seems like the fill character positioning has been changed (to left?). Adding `<< std::right` to line 1413 of v41's `trompeloeil.hpp` fixes the issue:

```c++
      os << std::setfill('0') << std::right << std::hex;
```

**Comment by rollbear** [comment]
Wow! OK, that is embarrassing. It's only been wrong since 2014. Goes to show how often people look at those. Fix coming tonight.

**Comment by rollbear** [comment]
Sometimes time flies. Fixed on main now. Leaving this open until a release has been tagged. Thank you for reporting.

**Comment by studoot** [comment]
Thanks for the quick fix!

I did kind of notice this a while back, but I think because I was debugging code translating between big- & little-endian reps, my brain kind of saw the 'swapped' nibbles as correct. Until yesterday, when I came to my senses :rofl:.

**Comment by rollbear** [comment]
Fix included in release v42
