### ISSUE TITLE
REQUIRE_CALL.AT_LEAST.IN_SEQUENCE has to got out of scope before the sequence gets completed

### ISSUE THREAD

**Issue by syyyr** [rollbear/trompeloeil#264]
Hi, since 45ef304, the behavior of this program has changed:
```cpp
#include <iostream>
#include <trompeloeil.hpp>

struct MockObject {
    MAKE_CONST_MOCK0(foo, void());
};

int main(int argc, char* argv[])
{
    MockObject obj;
    trompeloeil::sequence seq;
    REQUIRE_CALL(obj, foo()).TIMES(AT_LEAST(3)).IN_SEQUENCE(seq);
    obj.foo();
    obj.foo();
    obj.foo();
    std::cerr << "seq.is_completed() = " << seq.is_completed() << "\n";
}
```
Before 45ef304, it would print that the sequence is completed, but now it says that it's not. For the sequence to be completed, it would have to be like this:
```cpp
#include <iostream>
#include <trompeloeil.hpp>

struct MockObject {
    MAKE_CONST_MOCK0(foo, void());
};

int main(int argc, char* argv[])
{
    MockObject obj;
    trompeloeil::sequence seq;
    {
        REQUIRE_CALL(obj, foo()).TIMES(AT_LEAST(3)).IN_SEQUENCE(seq);
        obj.foo();
        obj.foo();
        obj.foo();
    }
    std::cerr << "seq.is_completed() = " << seq.is_completed() << "\n";
}
```
Is this change intentional? 45ef304 seems unrelated, but I am not sure.

Thanks.

**Comment by syyyr** [comment]
Note: With just `TIMES(3)`, it does not have to go out of scope for the sequence to be completed.

**Comment by rollbear** [comment]
This does not seem right. I'll look into it. Thanks for reporting.

**Comment by rollbear** [comment]
There's a fix on the branch [sequence_completion](https://github.com/rollbear/trompeloeil/tree/sequence_completion). Please try it out and tell me if there are remaining issues I have missed.

**Comment by syyyr** [comment]
It works for me, thanks!

**Comment by rollbear** [comment]
Let's leave this open, until it is included in a tagged release (probably quite soon.)

**Comment by rollbear** [comment]
Fix included in release v42
