### ISSUE TITLE
TROMPELOEIL_IMPLEMENT_MOCK with noexcept functions

### ISSUE THREAD

**Issue by ytimenkov** [rollbear/trompeloeil#275]
When I try to implement mock for interface which declares functions as `noexcept` it fails to compile:
(trompeloeil 42, gcc 10.2 with C++20):

```c++
struct My_iface
{
  virtual void func() noexcept = 0;
};

struct My_mock : public trompeloeil::mock_interface<My_iface>
{
  IMPLEMENT_MOCK0(func);
};
```

Results in compilation error like:
```
error: looser exception specification on overriding virtual function 'virtual trompeloeil::return_of_t<void()> My_mock::func()'
   53 |   IMPLEMENT_MOCK0(func);
      |                   ^~~~
note: overridden function is 'virtual void My_iface::func() noexcept'
   48 |   virtual void func() noexcept = 0;
      |                ^~~~
```

Changing to `TROMPELOEIL_IMPLEMENT_MOCK_(0, func, noexcept override);` works.

I use trompeloeil 42, but I don't see any support for adding extra keywords in the current main branck on GitHub.

I also wonder if it makes sense to allow arbitrary specifiers by user (like `&`, `&&`, `volatile`)?

**Comment by ytimenkov** [comment]
Or just `noexcept`-ness could be guessed / forwarded from the underlying function via `noexcept` operator / `noexcept(bool)` form.

**Comment by rollbear** [comment]
I see. You're right. I'll look into it.

**Comment by rollbear** [comment]
I will update the documentation. Just adding `noexcept` as a macro parameter works fine:
`IMPLEMENT_MOCK0(func, noexcept);`

I'll see if I can deduce it, that'd be nicer, but a quick test implementation failed.

**Comment by ytimenkov** [comment]
> Just adding noexcept as a macro parameter works fine

That is already good enough. I didn't realize that that `IMPLEMENT_MOCK` family accept variadic/extra parameters.

**Comment by rollbear** [comment]
Goes to show that the documentation needs a touch up, though. Thank you for reporting.

**Comment by rollbear** [comment]
Updated docs on `main`. Closing now. Feel free to reopen if you think the docs are insufficient or wrong.
