### ISSUE TITLE
How to match function call  (doubt)

### ISSUE THREAD

**Issue by josnih21** [rollbear/trompeloeil#276]
Hey there! I'm starting to play around with this library and I'm completely new using it, I got a lot of doubts on how to deal with it, and I would like to know if someone could help me with an implementation of a test I want to do: 

This is the case: 

I have a class that contains a system storage information 
```
class Storage_Config
{
  private:
    const string CONFIG_FILE_NAME= "blabla";
    string storage_type;
    ...
    ... 

  public:
    Storage_Config();
    string get_storage_type();
};
```
This function is being called from another class let's asume its called foo in my real code as: 
```
Foo::create_storage_system(){
  Storage_Config storage_config = Storage_Config()
  string storage_type = storage_config.get_storage_type()
  .... more code 
}
```
What I want to mock in my test (I'm using catch2) is that the `storage_config.get_storage_type() `function call,  returns a custom storage type, for example of type **"random"**

This is what I implemented in catch2 trying to mock the class `Storage_Config`

```
class Storage_Config_Mock : public Storage_Config {
public:
    MAKE_MOCK0(get_storage_type,string());
};

TEST_CASE("should create an instance of Random_Storage") {
    Storage_Config_Mock storageConfigMock;
    Garbled_Circuit_Storage* storage;
    {
      REQUIRE_CALL(storageConfigMock, get_storage_type()).RETURN("Random");
      storage = Foo::create_storage_system();
    }
    bool is_random_type = dynamic_cast<Random_Storage*>(storage) != nullptr;
    REQUIRE(is_random_type == true);
}
```

The issue comes when trying to call the **create_storage_system** function, that under the hood should call the **get_storage_type** function and returns the type that I specified in the return of the test, but I'm getting this error:

```
Expected storageConfigMock.get_storage_type() to be called once, actually
  never called
  "
```
I assume that I'm doing something wrong when creating the mock that is not doing any match with the real function that it's being called from **create_storage_system()** but I didn't manage to understand it, probably it's trivial solution, but I'm a lil bit noob with this stuff. 

Thanks in advance for the help, hope you can understand the problem, if there's any doubt we can continue talking about it here :) 

Kind regards 🥰

**Comment by rollbear** [comment]
You have several problems above.

To begin with, if you want a call to `get_storage_type()` via a pointer or reference to `Storage_Config`, then `get_storage_type()` must be virtual.

Second, your call to `Foo::create_storage_system()` must somehow access the `Storage_Config` (which needs to be your mock instead).

Your `Foo::create_storage_system()` creates a local instance of `Storage_Config`. It does not touch any mock.

**Comment by josnih21** [comment]
Finally I manage to fix my tests and mock the **Storage_Config** dependency @rollbear thansk for the support :)
