### ISSUE TITLE
Non-constexpr TIMES

### ISSUE THREAD

**Issue by Swassie** [rollbear/trompeloeil#283]
Hey

Currently the `TIMES` macro requires that its argument must be `constexpr`. This makes it not possible to use in a parametrized test or helper function where the number of calls depends on some parameter.

What is the reason behind this limitation, and can it be removed?

Thanks

**Comment by rollbear** [comment]
The reason is that the limits are expressed in the type system, and are used for many compile time checks. It may be possible to make it a runtime limit, probably with somewhat worse compile time error discovery, but it would be a substantial change.

**Comment by Swassie** [comment]
I think it would be a good change, especially since the workarounds (e.g. counter variables) aren't very good. The code would be cleaner and easier to understand if `TIMES` could be used in both cases.

**Comment by rollbear** [comment]
PR is welcome. I think it may be possible, but I don't know how to just yet.

**Comment by Swassie** [comment]
Sure, I can give it a try.

**Comment by DNKpp** [comment]
I'm giving this a bump, as I would really love to see this to be possible.

**Comment by rollbear** [comment]
This is now fixed on main after @DNKpp's PR was merged today. Thanks! I will close the issue once a release has been tagged.

**Comment by rollbear** [comment]
Included in release v49
