### ISSUE TITLE
find_package should be used to find catch

### ISSUE THREAD

**Issue by yurivict** [rollbear/trompeloeil#286]
[here](https://github.com/rollbear/trompeloeil/blob/main/CMakeLists.txt#L53)

**Comment by rollbear** [comment]
Thank you. Yes, I agree. I started working on this before I saw your issue. It takes a little while because I need to update my CI build containers (used also for other projects) to aid this, but it'll all be so much cleaner when done.

**Comment by rollbear** [comment]
Done on `main` now. I'm leaving this open until a release has been tagged.
