### ISSUE TITLE
VS 2017RC compilation errors

### ISSUE THREAD

**Issue by rollbear** [rollbear/trompeloeil#29]
VS 2017RC does not accept the self test program `compiling_tests.cpp`. The compilation error on `.IN_SEQUENCE(seq1, seq2)` indicates a preprocessing error, but preprocessing to a file reveals code that looks correct and that cannot possibly result in the same compilation error.

I believe that this is a bug in VS 2017 RC, but I have been unable to make a scaled down reproduction of the error which can be used in a bug report, and my VisualStudio expertise is too limited.

**Comment by mlimber** [comment]
With one version of the 2017RC, I tried this (line breaks added):
```
>cl /EHsc /I . compiling_tests-pre.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.10.24728 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

compiling_tests-pre.cpp
compiling_tests.cpp(949): fatal error C1001: An internal error has occurred in the compiler.
(compiler file 'msc1.cpp', line 1469)

To work around this problem, try simplifying or 
changing the program near the locations listed above.

Please choose the Technical Support command on the 
Visual C++ Help menu, or open the Technical Support
help file for more information

Internal Compiler Error in C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.10.24728\bin\HostX86\x86\cl.exe.  

You will be prompted to send an error report to Microsoft later.
```
The line in question is:
```cpp
TEST_CASE_METHOD(Fixture, "wildcard matches parameter value type", "[matching]")
{
  {
    U u;
    REQUIRE_CALL(u, func_v(_)); // <---- 949
    u.func_v(1);
  }
  REQUIRE(reports.empty());
}
```
Commenting it out moves the error to the next similar line (959).

I'm updating to the latest RC to see what happens. VS 2015 Update 3 builds it without problem (but has a test failure when running).

**Comment by rollbear** [comment]
Interesting in many ways.

That line isn't using any advanced stuff at all, really. Very "basic" TMP. It has also already compiled loads of similar constructs above that line. An internal compiler error is kind of handy, though. Are you forwarding a report to MS?

On my VS 2015 Update 3 it runs flawlessly, but I admit I'm not using the latest version of Catch. Which test fails and what's the message?

**Comment by mlimber** [comment]
If I preprocess the file, the line that breaks (autoformatted by VS) is:
```cpp
  auto trompeloeil_call_obj_943 =
      ::trompeloeil::call_validator(
          static_cast<std::decay_t<decltype((u).func_v(_))> *>(nullptr), (u)) +
      decltype((u).trompeloeil_tag_func_v(_))::maker((u), "compiling_tests.cpp",
                                                     943, "u"
                                                          "."
                                                          "func_v(_)")
          .func_v(_);
```
Which I break down into its constituent parts:
```cpp
    using V = std::decay_t<decltype(u.func_v(_))>*;
    using TV = decltype(u.trompeloeil_tag_func_v(_));

    auto val = ::trompeloeil::call_validator( static_cast<V>(nullptr), u);
    auto tVal = TV::maker( u, "compiling_tests.cpp", 943, "u.func_v(_)");

    auto x = tVal.func_v(_);  // <----------------- This line is the problem
    
    auto validator = val + x;
```
Dropping that line (and the `+x` on the next) gets rid of the problem.

**Comment by mlimber** [comment]
Re the failure on VS2015:
```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compiling_tests is a Catch v1.5.6 host application.
Run with -? for options

-------------------------------------------------------------------------------
matching calls are traced
-------------------------------------------------------------------------------
compiling_tests.cpp(4017)
...............................................................................

compiling_tests.cpp(4063): FAILED:
  REQUIRE( std::regex_search(os.str(), std::regex(re)) )
due to unexpected exception with message:
  compiling_tests.cpp:4023
  obj1.getter(_, _) with.
    param  _1 == 3
    param  _2 == foo

  compiling_tests.cpp:4024
  obj2.foo("bar") with.
    param  _1 == bar
  threw exception: what() = nonono

  compiling_tests.cpp:4026
  obj1.getter(ANY(int)) with.
    param  _1 == 4
   -> 5

  compiling_tests.cpp:4028
  obj2.foo("baz") with.
    param  _1 == baz
  threw unknown exception

  regex_error(error_complexity): The complexity of an attempted match against a
  regular expression exceeded a pre-set level.

===============================================================================
test cases: 233 | 232 passed | 1 failed
assertions: 351 | 350 passed | 1 failed
```
(I think I mentioned this in a different thread somewhere.)

**Comment by rollbear** [comment]
That sounds familiar, yes. I wonder why I don't get that error, though.

**Comment by mlimber** [comment]
I had VS215U3 create me a project from existing code (File | New > | Project from existing code ...). I built the project in x86 and x64 for Debug and Release. (I had to add /bigobj for at least one of them to get it to build.) Debug x64 passes, but all the others fail with the given message. Perhaps you were looking at that one config?

**Comment by mlimber** [comment]
I tried your master with the now-released VS 2017, and alas, it crashes in the same spot with the following:
```
1>------ Build started: Project: trompe, Configuration: Debug Win32 ------
1>compiling_tests.cpp
1>compiling_tests.cpp(949): fatal error C1001: An internal error has occurred in the compiler.
1>(compiler file 'msc1.cpp', line 1469)
1> To work around this problem, try simplifying or changing the program near the locations listed above.
1>Please choose the Technical Support command on the Visual C++
1> Help menu, or open the Technical Support help file for more information
1>compiling_tests.cpp(797): note: while compiling class template member function 'trompeloeil::call_modifier<trompeloeil::call_matcher<sig,unknown-type>,tag,trompeloeil::matcher_info<sig>> U::trompeloeil_tag_type_trompeloeil_797::maker_obj<U>::func_v(U &&...)'
1>        with
1>        [
1>            sig=void (int),
1>            tag=U::trompeloeil_tag_type_trompeloeil_797
1>        ]
1>Done building project "trompe.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```
Commenting stuff out just moves the compiler crash to the next test function.

**Comment by rollbear** [comment]
Rats. But thanks @mlimber . Appreciate your help.

**Comment by xiangfan-ms** [comment]
If you want to get unblocked, you can try this source workaround (in trompeloeil.hpp):

#if 1
template <typename... U>
struct param_helper {
using type = decltype(std::make_tuple(std::declval<U>()...));
};
template <typename ... U>
using param_t = typename param_helper<U...>::type;
#else
template <typename ... U>
using param_t = decltype(std::make_tuple(std::declval<U>()...));
#endif

**Comment by rollbear** [comment]
This is excellent. Thanks @xiangfan-ms. Do you want to submit a pull request to get credit for your work, or do I just add the fix?
My attempts to install VI2017 still fails (installation hangs at 97% complete) so I can't verify.
@mlimber can you verify the work-around for me?

**Comment by rollbear** [comment]
@xiangfan-ms a pull request for this, should you want to submit one, would be best directly on 'master', and include a mention of VS2017 in README.md.

**Comment by mlimber** [comment]
Pull request issued. It does build on VS 2017 with that change. I did not test GCC/Clang. Note also that the test results are the same as VS 2015: Debug x64 passes but Release x64, Debug x86, and Release x86 all fail with the error about regexes.

**Comment by rollbear** [comment]
I've tested on gcc/clang, so I'm not worried. Just waiting for the mails from travis-ci before accepting the PR. I really appreciate your help here @mlimber. Thanks!

**Comment by rollbear** [comment]
Fixed in v24

**Comment by mlimber** [comment]
I note that [Microsoft has said](https://developercommunity.visualstudio.com/content/problem/25323/internal-error-in-the-compiler-when-building-heavi.html) that this is fixed in an upcoming release.
