### ISSUE TITLE
Object naming via __LINE__ prevents me from abusing macros even more -- cannot put two REQUIRE_CALL in one line

### ISSUE THREAD

**Issue by jktjkt** [rollbear/trompeloeil#39]
My mock simulates I/O communication, and a class that I'm testing makes several I/O operations from within its constructor. I'm using Catch. Here's how my mock looks like:

```cpp
class FakeSerial: public IO:blahblah
{
public:
    MAKE_MOCK1(readWithTimeout, std::string(ssize_t), override);
    MAKE_MOCK1(write, void(const std::string &), override);
};

#define FAKE_SERIAL_INIT \
    auto serial = std::make_shared<FakeSerial>(); \
    trompeloeil::sequence seq1;

#define FAKE_WRITING(DATA) \
    REQUIRE_CALL(*serial, write(DATA)) \
    .IN_SEQUENCE(seq1)

#define FAKE_READING(DATA) \
    REQUIRE_CALL(*serial, readWithTimeout(-1)) \
    .IN_SEQUENCE(seq1) \
    .RETURN(DATA)
```

I can pretty easily setup fixtures like this:

```cpp
TEST_CASE("module detection") {
    FAKE_SERIAL_INIT;
    FAKE_WRITING("command 1");
    FAKE_READING("response 1");
    FAKE_WRITING("command 2");
    FAKE_WRITING("response 2");
    FAKE_WRITING("command 3");
    FAKE_WRITING("response 3");
    FAKE_WRITING("command 4");
    FAKE_WRITING("response 4");

    MyClass m;
    // do more tests here
}
```

I would like to have several top-level ``TEST_CASE`` blocks, and I would like to not have to repeat the four ``FAKE_READING``/``FAKE_WRITING`` stanzas, and a first idea on how to approach this is like this:

```cpp
#define INITIAL_CHAT \
    FAKE_WRITING("command 1"); \
    FAKE_READING("response 1"); \
    FAKE_WRITING("command 2"); \
    FAKE_WRITING("response 2"); \
    FAKE_WRITING("command 3"); \
    FAKE_WRITING("response 3"); \
    FAKE_WRITING("command 4"); \
    FAKE_WRITING("response 4");

TEST_CASE("...") {
  INITIAL_CHAT
}
```
This doesn't work, though, because Trompeloeil uses the ``__LINE__`` macro to create an uniquely named object for each ``REQUIRE_CALL``, but because of macro expansion, all of these ``REQUIRE_CALL``s are defined on the same line, and therefore there's a name clash.

I tried to made a trivial change to `` TROMPELOEIL_ID`` to use a ``__COUNTER__``, but that didn't work -- I assume that these identifiers actually need to be reused from time to time.

I know that I can make a helper method which returns a vector of expectations, but I think that I'm being reasonably reasonable when I want to wrap several ```REQUIRE_XXX``` macro invocations within a single macro, am I not?

**Comment by rollbear** [comment]
I see. Generally speaking __COUNTER__ is very problematic, but it'd be perfectly harmless when generating the name for the expectation variable.

I'll experiment with this tonight and see what I can come up with. I think all that's needed is to use another means to generate the name of the hidden local variable in `TROMPELOEIL_REQUIRE_CALL_()`

**Comment by rollbear** [comment]
OK, seems easy enough. Can you try the current `develop` branch? I pushed an update that uses `__COUNTER__` for the local variable names, but keeps using `__LINE__` for everything else.

**Comment by jktjkt** [comment]
Sorry for a delay and thanks for a nice fix. I can confirm that it fixes the issue I reported, the test you added is reasonable IMHO.

In the end, this macro usage looks good to me. IMHO it's nicer than my workaround with a function returning a ``std::vector<std::unique_ptr<trompeloeil::expectation>>``. Thanks.

**Comment by rollbear** [comment]
OK. Good. I'll leave this open for others to see, until it's merged into a tagged release.

**Comment by rollbear** [comment]
Fixed in v25
