### ISSUE TITLE
Check whether all expectations have been already fulfilled

### ISSUE THREAD

**Issue by jktjkt** [rollbear/trompeloeil#42]
I'm writing tests for a component, let's call it a Driver. The Driver talks to a piece of HW which I'm mocking with Trompeloeil. The test code doesn't access the Driver directly; everything is marshaled through an external component ([sysrepo](http://www.sysrepo.org/), let's call it the Marhal) which provides its own API for exercising the Driver's functionality. The Marshal creates a worker thread in which it handles all interaction with my Driver. In my main thread, I open another connection to Marshal and ask it to perform some actions which are *eventually* translated into some calls to my Driver. However, everything is asynchronous, so I'm currently using code which looks roughly like this:

```cpp
auto hw = std::make_shared<MockedHw>();
auto driver = std::make_shared<Driver>(hw);
Marhal::register("rocket-launcher", d);
// That created a background thread from deep within Marhal's bowels.
// Everything which touches driver/hw will execute in that background thread.

trompeloeil::sequence s;
REQUIRE_CALL(*hw, write("launch missiles")).IN_SEQUENCE(s);
REQUIRE_CALL(*hw, read()).RETURNS("they're flying now").IN_SEQUENCE(s);

auto conn = new Marhal::connect();
conn->triggerAction("rocket-launcher", "launch-missiles");
// Marhal's glue code calls something on my Driver, and the Driver calls
// hw->write("launch missiles") followed by hw->read() which is expected
// to return "they're flying now".
// The problem is that because Marshal is a networked thing, it sometimes takes
// an unspecified time for it to finish its business and process everything.

std::this_thread::sleep_for(500ms);
```

How should the timeout look like? If it's too short, then there's a risk of false positives when the system is "too slow" for whatever reason (I'm seeing this in my CI with shared VMs now). If the timeout is too long, though, then each run of ``ninja test`` takes too long because I have dozens of similar test cases like the one above, so time timeouts add up.

I would like to replace ``this_thread::sleep_for(500ms)`` with something like this:

```cpp
auto start = std::chrono::system_time::now();
while (s.hasUnmatchedEpectations() && std::chrono::system_time::now() - start < 2s) {
  std::this_thread::sleep_for(50ms);
}
std::this_thread::sleep_for(300ms);
```

Is this something that you think would make some sense in Catch? I know that I could add side effects to my ``REQUIRE_CALL`` expectations and that I can build a parallel registry of everything that is supposed to happen, but it occurs to me that Trompeloeil already has something like this for its own tracking. Is it possible to observe this from the outside?

If a feature like this is a good match for Trompeloeil, what what about an API based on ``std::promise``?

**Comment by rollbear** [comment]
Hmmm. To ask whether there are expectations remaining for a specific mocked function would not be very difficult to add. To ask if generally there are any remaining expectations for a mock object would be trickier, but maybe I could come up with a way to do it, given enough time to think about it. (for each mocked function there's a list of active expectations, but there's no connection at all between different mocked functions.)

Your use case is a bit troubling, though. A dependency on something you do not have control over, in this case the thread scheduler, is something you really want to avoid in unit tests. `sleep` is definitely a warning signal. I have, as my personal rule of thumb, an upper limit of 5s as acceptable for the run of an entire test suite consisting of typically hundreds of tests (on my laptop, the `compiling_tests.cpp` self test for Trompeloeil runs in 41ms.)

For threaded applications, this means you have to model your tests differently, such that you don't typically use threading in the tests, but you use the inter-thread boundary as a test boundary. The up side of that is that you have fine grained control of all possible interleaved events and no unpredictability in the test runs. The down side is that those unit tests will never catch a data race bug.

**Comment by jktjkt** [comment]
> A dependency on something you do not have control over, in this case the thread scheduler, is something you really want to avoid in unit tests.

Indeed, but if one thinks about them as "integration tests", it starts making sense again. IMHO. I specifically want to test how the unmodified external Marshal integrates with my Driver.

Thanks for considering this.

**Comment by rollbear** [comment]
On branch `develop`, you can now ask sequence objects if they have run to completion using the query:
```Cpp
if (seq.is_completed()) ...
```
I've given up on the idea to check whether a mock object has pending expectations. It is possible in some cases, but not generally possible for all constructions.

It would, however, be quite easy to turn it around and ask expectations if they are saturated or still pending.

**Comment by jktjkt** [comment]
Thanks, I can confirm that this change helped me do what I want to achieve (and sorry for not confirming it earlier, I forgot about that).

**Comment by rollbear** [comment]
Excellent. I've just expanded on this a bit. You can ask a `trompeloeil::expectation` if it `is_satisfied()` or `is_saturated()`.

```Cpp
auto exp = NAMED_REQUIRE_CALL(x, y);
...
if (exp->is_saturated()) ...
```

`is_satisfied()` is true if the expectation object can be destroyed without reporting a missing call, i.e. the minimum number of calls has been reached.

`is_saturated()` is true if a call will be reported it as unexpected, i.e. the maximum number of calls has been reached.

**Comment by rollbear** [comment]
Just tagged v26 where these are implemented and documented, so closing now.
