### ISSUE TITLE
How to mock a policy based design

### ISSUE THREAD

**Issue by nedrebo** [rollbear/trompeloeil#43]
When using this design the instance of the mock object may not be available. It would be nice to not alter the API just to allow mocking. Is that supported, I could not find anything about it in the docs or faq.

Small (pseudo) code sample

**The API:**
```
template<typename T>
class Foo : private T
{
    using T::func;
public:
    int doStuff() { return func(); }
}
```
**Test code**
```
TEST
{
    MockObject
    {
      MAKE_MOCK0(func, int());
    };

    Foo<MockObject> sut;

    // How to add requirements?

    sut.doStuff();
}
```
Is it possible to add the requirements to the mock class so that they are set in the constructor? Something like this:

```
MockObject
{
  MAKE_MOCK0(func, void());
  ADD_REQUIREMENT(foo)
      .TIMES(1)
      .RETURN(1)
};
```

**Comment by rollbear** [comment]
I'm not entirely sure that I understand, but yes, you can add expectations in a constructor, as long as you have somewhere to keep the expectation alive. For example, you could do:

```Cpp
struct MockObject
{
  MAKE_MOCK0(func, int());
  MockObject()
  : expect_func_call(NAMED_REQUIRE_CALL(foo, func()).RETURN(1))
  {}
  std::unique_ptr<trompeloeil::expectation> expect_func_call;
};
```

`.TIMES(1)` in your pseudo code is not needed. Once is the default for `REQUIRE_CALL()`.

**Comment by rollbear** [comment]
For the sake of completeness, there are, of course, also completely different approaches. For example:

```Cpp
struct MockObject
{
  MAKE_MOCK0(func, int());
  MockObject() { instances.push_back(this); }
  static std::vector<MockObject*> instances;
};

TEST(...)
{
  Foo<MockObject> obj;
  REQUIRE_CALL(*MockObject::instances.back(), func())
   .RETURN(1);
  // rest of test...
}
```

The advantage with an approach like this, over the previous one, is better control of the life time of your expectations.

**Comment by nedrebo** [comment]
Thanks that will work!

My example may be overly simplified. The problem is that the test code have no way to access the instance of the Mock object as it is being instantiated deep down in a template class.

Your solution seem just like what I hoped for. And by using default member initializer it would be possible to write a macro for it as (I guess, no macro expert).

```
struct MockObject
{
  MAKE_MOCK0(func, int());

  std::unique_ptr<trompeloeil::expectation> expect_func_call
  {
      NAMED_REQUIRE_CALL(foo, func()).RETURN(1)
  };
};
```

**Comment by nedrebo** [comment]
Yes been thinking about lifetime control as well. You had something about it in the cook book also, didn't dive into that yet. The alternative static trick was nice as well (for test code :)).
