### ISSUE TITLE
Do not know how to mock destructors

### ISSUE THREAD

**Issue by francoisgenolini** [rollbear/trompeloeil#5]
On Windows 10 (latest update), I have a Visual Studio 2015 native C++ unit test project and I am testing a class that attempts to delete a mocked object.
This causes an abort.
My current fix is to have all interfaces that can be mocked implement an IsMock() method, and get all my code to skip deleting if the object is a mock.
I would rather be able to `ALLOW_DESTRUCTOR(mock)`, and be able to run some code upon destruction, for example count how many times the destructor is called (not a kind of bug that I want to let through).
Even better would be  `ALLOW_DESTRUCTOR(mock).TIMES(AT_MOST(1))`

Could help getting destructors mocked with trompelœil ?

**Comment by rollbear** [comment]
Hmm, I'm a bit confused. Deleting an object with mocked member functions shouldn't cause any problems on its own. Are these trompeloeil::deathwatched<> mocks? Are there other unfulfilled expectations pending? Abort also sounds wrong. What unit-test framework do you use?

The `IsMock()` construction feels like an abomination that should not be required, so I *really* want to help you get out of that mess.

**`ALLOW_DESTRUCTION(...)`** is an interesting idea to complement **`REQUIRE_DESTRUCTION(...)`**. I have to think about it.

For now I see two alternatives.

You can use **`REQUIRE_DESTRUCTION(...)`**, but this seems too strong for your needs or you would've already tried it (just mentioning it for completeness.)

You could work around it by adding an extra mock-function, called from the destructor, and use an **`ALLOW_CALL(...)`** on that function.

```Cpp
class Mock
{
public:
  MAKE_MOCK0(died, void());
  ~Mock() { died(); }
};

a_test()
{
  auto m = new Mock;
  non_fatal_func(m); // delete m would be illegal
  ALLOW_CALL(*m, died());
  maybe_fatal_func(m); // delete m is allowed, but not required
}
```

Also, don't forget, mocks aren't magical in any way, just horrendous macros. You can add your own member functions, including destructor, as you please to your mock classes.

By definition an object cannot be destroyed more than once, so I'd rather not use any .TIMES() construction, even if I think I undestand your intent.

**Comment by francoisgenolini** [comment]
Hi,

Thanks for the very quick response.  This is my first day ever with C++ mocking... so not everything makes sense to me just yet.
I amusing the simplest code possible, with no death watch.
I use the `Microsoft::VisualStudio::CppUnitTestFramework` that you get when you create a new Visual Studio 2015 native C++ unit test project.
I am also struggling with the `set_reporter` as it does not supply the faulting function name that is so useful in the `__LineInfo` structured passed to `Assert::Fail()`

I do not actually require destruction at this point, I merely want to check that my code only calls it at most once.  I must also admit that I have failed to get REQUIRE_DESTRUCTION to compile yet.
I thought I would try to mock all my objects of a particular type with a single mock, and therefore allow multiple destructions.  The single mock would be used as a state machine for model based testing.

I am currently looking at a number of alternatives for model based testing, such as NModel and SpecExplorer.  I am wondering how far mocking can be twisted to be used as a model based testing framework.

Thanks for your suggestions, I will try them.

**Comment by francoisgenolini** [comment]
Here is my first attempt at integrating with MSTest:
`
			TEST_CLASS_INITIALIZE(SetTrompeloeilReporter)
			{
				set_reporter([](severity s,
					char const *file,
					unsigned long line,
					const std::string& msg)
				{
					size_t fileLen = strlen(file) + 1;
					wchar_t* wideFile = L"";
					if (fileLen > 0)
					{
						wideFile = new wchar_t[fileLen]();
						size_t convertedChars = 0;
						mbstowcs_s(&convertedChars, wideFile, fileLen, file, _TRUNCATE);
					}

					__LineInfo lineInfo((const wchar_t*)wideFile, "", line);
					size_t messageLen = strlen(msg.c_str()) + 1;
					wchar_t* wideMessage = L"";
					if (messageLen > 0)
					{
						wideMessage = new wchar_t[messageLen]();
						size_t convertedChars = 0;
						mbstowcs_s(&convertedChars, wideMessage, messageLen, msg.c_str(), _TRUNCATE);
					}

					if (s == severity::fatal)
					{
						Assert::Fail(wideMessage, &lineInfo);
					}
					else
					{
						Logger::WriteMessage(wideMessage);
					}
				});
			}
`

**Comment by francoisgenolini** [comment]
I had implemented died and used it for a `Mock` on the stack (not on the heap).
Now that I have a `new Mock`, the first delete works, and the second one causes an access violation.
Good ;-)

**Comment by rollbear** [comment]
I don't think the language allows for a reliable check that an object is not deleted twice - the second attempt would be undefined behaviour. It might work, but it's not reliable.

Example:

```Cpp
int* p1 = new int{1};
delete p1;
int* p2 = new int{2};
delete p1;
```

Depending on the heap implementation, it may be very likely that `*p2` is allocated on the same address as `*p1` was (reusing a hot address makes for good cache-locality, so it's very performance friendly.) In that case, `delete p1` is, although strictly speaking illegal, just deallocating the second object.

I'm very unfamiliar with Visual Studio, I don't really ever work in it, so I think I need some help.

Is MSTest included in Visual Studio, or is it something I have to download? How do I create a test program and where do I find documentation on how to use it? My google-fu is failing me here.

I will be away most of the day today, but I'll try to look into this tonight.

**Comment by francoisgenolini** [comment]
I believe that there is no way to detect that a pointer is already deleted.  I was actually looking to get the mock to fake delete, and not actually touch the heap at all.  That way counting the deletes will be possible.

Visual Studio 2015 Community Edition comes with Microsoft unit tests included for free.
I start a native C++ unit test by clicking `File | New | Project...` and then select `Installed | Templates | Other Languages | Visual C++ | Test | Native Unit Test Project`

This automatically adds the correct folder to the include path:
`C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\UnitTest\include`

Of particular interest is `CppUnitTest.h` which contains the documentation for the Microsoft unit tests in the comments.

Regards,

**Comment by rollbear** [comment]
It became a bit later than I hoped for, so I've only done this somewhat superficially.

For a adapting to MSTest, this seems to work fine, and is much shorter than your version:

```Cpp
  using namespace trompeloeil;
  set_reporter([](severity, char const* file, unsigned long line, std::string const& msg) {
    std::wstring wideMsg(msg.begin(), msg.end());
    std::wstring wfile;
    if (line > 0) wfile.append(file, file + strlen(file));
    __LineInfo loc(wfile.c_str(), "", line);
    Assert::Fail(wideMsg.c_str(), line == 0 ? nullptr : &loc);
  });
```

In the case of calling an unexpected mock function, you still get the name of the failed test and file/line where it begins in the message, so that's alright, I think.

Please try it. If you think it's fine, I'll add it to the documentation.

As for trying to detect double deletion via any mocking framework, I remain unconvinced. Access to an already destroyed object is undefined behaviour. The technique may work for simple concrete classes, but I think the chances of success in the face of virtual destructor is minimal, given that every step up the inheritance ladder of destruction changes the virtual function table pointer. Even if you get the result you want, there is no guarantee at all that the next compiler update will keep that behaviour.

I'm not familiar with the tools available for this in the Windows world, although I'm sure there are several to choose from. In a Linux world I'd suggest compiling with the G++ or Clang -fsanitize=undefined, or run in Valgrind.

Another alternative, but it's no small feat, is to write your own debug-heap.

**Comment by francoisgenolini** [comment]
Thanks,

I had - briefly - managed to get double delete detection using FakeIt, but one compiler update on (as you guessed), this ABI vmt modification trick failed.  The idea there, I guess, was to hijack the destructor for mock objects (they never actually get deleted, a Fake is inserted in the VMT).
I will use plain profiling (Valgrind and co, or port to XCode and use the nice tools there) to get some statistics on object lifetimes, this usually picks up undesired trends.

Thanks for the `set_reporter`, I will try it tomorrow.

Regards,

**Comment by francoisgenolini** [comment]
Thanks for the `set_reporter`, it works for me.
For Visual Studio programmers, it might be more user friendly to give a full example such as:

``` C++
#include "stdafx.h"
#include "CppUnitTest.h"
#include "trompeloeil.hpp"

namespace NativeUnitTest
{
	using namespace Microsoft::VisualStudio::CppUnitTestFramework;
	using namespace trompeloeil;

	struct IFoo
	{
		virtual bool bar(int) = 0;
	};

	class FooMock : public IFoo
	{
	public:
		MAKE_MOCK1(bar, bool(int));
	};

	TEST_CLASS(UnitTest1)
	{
		TEST_CLASS_INITIALIZE(SetTrompeloeilReporter)
		{
			set_reporter([](severity, char const* file, unsigned long line, std::string const& msg) {
				std::wstring wideMsg(msg.begin(), msg.end());
				std::wstring wfile;
				if (line > 0) wfile.append(file, file + strlen(file));
				__LineInfo loc(wfile.c_str(), "", line);
				Assert::Fail(wideMsg.c_str(), line == 0 ? nullptr : &loc);
			});
		}

	public:
		TEST_METHOD(TestMethod1)
		{
			FooMock fooMock;
			REQUIRE_CALL(fooMock, bar(ANY(int)))
				.RETURN(true)
				.TIMES(AT_LEAST(1));
		}
	};
}
```

A screen shot would also be very welcome, so that people can really picture how things should look:

![image](https://cloud.githubusercontent.com/assets/12999427/11625693/c2089f9c-9cd4-11e5-8d58-b5fe4bd1b359.png)

**Comment by rollbear** [comment]
Thanks for the suggestion. I'll update the documentation.

If you don't mind, I'll close this issue, since I think the question has been resolved, although perhaps not quite the way you hoped for?

**Comment by francoisgenolini** [comment]
Works for me, thanks a lot
I learned much here
