### ISSUE TITLE
Using expectations on more than one mock object at a time

### ISSUE THREAD

**Issue by rcdailey** [rollbear/trompeloeil#50]
Some tests I write involve verifying that two or more objects are affected in the same way. For example, when I have "subscribers" that are attached to a "publisher", I want all the subscribers to receive the same calls with the same arguments. At the moment I accomplish this by repeating the expectation macro once for each "subscriber":

```
auto& um = CUpdateManager::Instance();

MockUpdateReceiver m1, m2;

um.AddReceiver(&m1);
um.AddReceiver(&m2);

REQUIRE_CALL(m1, NeedAnyUpdates()).RETURN(true);
REQUIRE_CALL(m2, NeedAnyUpdates()).RETURN(true);
REQUIRE_CALL(m1, Update(0.f));
REQUIRE_CALL(m2, Update(0.f));

um.Update(0.f);
```

It would be more ideal to be able to somehow do this:

```
REQUIRE_CALL({m1, m2}, NeedAnyUpdates()).RETURN(true);
REQUIRE_CALL({m1, m2}, Update(0.f));
```

Is this currently possible, and if not would you be willing to make some changes to support this?

**Comment by rollbear** [comment]
It is not currently possible, no.

A possible work around is:

```Cpp
template <typename T>
auto needsUpdate(T&  t)
{
  return NAMED_REQUIRE_CALL(t, NeedAnyUpdates()).RETURN(true);
}

template <typename ... T>
auto theseNeedUpdates(T& ... t)
{
  std::vector<std::unique_ptr<trompeloeil::expectation>> rv;
  std::initializer_list<int>{(rv.push_back(needsUpdate(t)),0)...};
  return rv;
}
```
The `initializer_list<int>` thingie is an ugly work around for the lack of fold-expressions in C++14. It forces the calls to `needsUpdate()` for each `t`, and uses the comma operator to add a 0 to the `initializer_list`.

Then, in your test, you write:

```Cpp
  auto needsUpdates = theeseNeedsUpdates(m1, m2); // vector of expectations
  ... // things that may call NeedAnyUpdates()...
```

Is a smoother work solution very important for you? I do currently not have any idea how to implement it, so a smooth solution may take a while to get in place.

**Comment by rcdailey** [comment]
That feels very over-engineered. I didn't mean to imply that initializer lists were *required*. I'd be fine with something like this (if it makes it cleaner):

```
auto& um = CUpdateManager::Instance();

std::vector<MockUpdateReceiver> receivers(2);

um.AddReceiver(&receivers[0]);
um.AddReceiver(&receivers[1]);

REQUIRE_CALL(receivers, NeedAnyUpdates()).RETURN(true);
REQUIRE_CALL(receivers, Update(0.f));

um.Update(0.f);
```

And internally you can have special overloads for `std::vector<T>` and just run a loop that forwards to the version taking a single mock (`T`)

**Comment by rollbear** [comment]
I agree, but currently the presented work-around is the best I can offer. I'll try to figure out a better way.

**Comment by rcdailey** [comment]
I'll go ahead and close this one, it's a bit of an edge case and likely not going to be a good ROI. I haven't run into this too often myself, even.
