### ISSUE TITLE
Make 'override' a default

### ISSUE THREAD

**Issue by rcdailey** [rollbear/trompeloeil#51]
It would be nice if `override` was used by default in the `MAKE_MOCK` and `MAKE_CONST_MOCK` macros. You could turn this on with a preprocessor flag, or based on language version (`__cplusplus` I think). Is there a reason this isn't assumed by default? I can't imagine it's possible (or meaningful) to mock non-virtual interfaces since there is no dispatch without it.

**Comment by rollbear** [comment]
It is a firm belief om mine that java-style inheritance of interfaces is much over used in C++, and making that unfortunate  pattern the default would not be a good thing.

If the language offered enough reflection support to recognise the situation, I'd agree, but to place a burden of "not override" (no idea how to implement, btw) for good design seems like a poor choice.

**Comment by rcdailey** [comment]
I guess I'm not sure what you're saying. IMHO, override solves a very specific problem:

```
class Base
{
public:
    virtual void foo(int) {}
};

class Derived : public Base
{
public:
    virtual void foo(float) {} // Not a virtual override; won't be called and this "error" is silent and difficult to track down sometimes
};
```

In the above example, the *intent* is to override `Base::foo()`, but because of a simple typo, or (most commonly) the interface of the base class changed but not the derived type, this went undetected. The simple addition of `override` here solves what I argue is a common case:

```
class Base
{
public:
    virtual void foo(int) {}
};

class Derived : public Base
{
public:
    virtual void foo(float) override {} // Compiler error!
};
```

When mocking interfaces, I think the most common case (intent) is to override existing functions, **not** provide new interfaces (that wouldn't make much sense inside of a mock class wrapped by Trompeloeil, IMHO).

Since I feel the common case here is to `override` members of the interface, it seems odd to me to require that `override` be explicitly specified. It becomes boilerplate and is error prone as I might forget to specify the 3rd argument to your `MAKE_MOCK` macro.
