### ISSUE TITLE
fixed: Restore warnings for Clang builds

### ISSUE THREAD

**Issue by AndrewPaxie** [rollbear/trompeloeil#55]
The warnings defined in `CMakeLists.txt` are not being applied to
Clang builds.  An examination of a recent build on Travis e.g.
Job 386.4/line 782

https://travis-ci.org/rollbear/trompeloeil/jobs/272340182

shows the command
```
/usr/bin/clang++-4.0    -g -I/home/travis/build/rollbear/trompeloeil/build/catch -I/home/travis/build/rollbear/trompeloeil/include    -fsanitize=address,undefined -std=gnu++14 -o CMakeFiles/self_test.dir/test/compiling_tests.cpp.o -c /home/travis/build/rollbear/trompeloeil/test/compiling_tests.cpp
                    ^^^^ warnings missing
```

The cause is the cmake variable `CMAKE_COMPILER_IS_GNUCXX` returning empty
for a Clang compiler.

Restore the intended warning list by using `CMAKE_CXX_COMPILER_ID` instead.

**Comment by rollbear** [comment]
Fixed. Keeping open until included in a tagged release.

**Comment by rollbear** [comment]
Fix included in release v29
