### ISSUE TITLE
Expectations specified in sub-scopes get deleted at scope exit

### ISSUE THREAD

**Issue by francoisgenolini** [rollbear/trompeloeil#6]
Hi,

How should I code multiple identical expectations?

I have an array of mock objects, all requiring identical (or similar) expectations to be set.

``` C++
				ALLOW_CALL(mocks[0], foo());
				ALLOW_CALL(mocks[1], foo());
				ALLOW_CALL(mocks[2], foo());
```

I would rather prefer to have a loop construct, such as:

``` C++
				for (int i = 0; i < 3; i++)
				{
					ALLOW_CALL(mocks[i], foo());
				}
```

Also, for large number of unit tests, I would like to have common expectations set-up in methods and functions.

``` C++
				Mock mock;
				mock.set_expectations_0();
				interface_func(&mock);
```

This however does not work as ALLOW_CALL creates a stack object that gets deleted when the for loop or the method / function exits.

Would it be possible to have all expectations added to the internal state of the mock object itself, so that expectations could be created in sub-scopes (functions, methods, loops...)?

Regards,

**Comment by SimonKagstrom** [comment]
I use NAMED_ALLOW_CALL and a vector of expectations, i.e.,

```
std::vector<std::unique_ptr<trompeloeil::expectation>> allowedExpectations;
[...]
for (i...)
  allowedExpectations.push_back(NAMED_ALLOW_CALL(mock[i], foo());
[...]
```

**Comment by francoisgenolini** [comment]
Thanks a lot.

I saw the documentation, but I could not quite make out how to use it ;-)  Sorry about that.

```
If the scoped lifetime rules are unsuitable, there are also thee named versions of the expectations.

NAMED_ALLOW_CALL(...)
NAMED_REQUIRE_CALL(...)
NAMED_FORBID_CALL(...)
These do the same, but they creata a std::unique_ptr<trompeloeil::expectation>, which you can bind to variables that you control the life time of.
```

**Comment by francoisgenolini** [comment]
Works for me
