### ISSUE TITLE
Things to know about compiling Trompeloeil on Ubuntu 17.10

### ISSUE THREAD

**Issue by AndrewPaxie** [rollbear/trompeloeil#63]
Not an issue, just an alert for the confused, who may be asking,
"Why doesn't Trompeloeil compile on Artful Aardvark (for my compiler, library)?"

Artful Aardvark a.k.a. Ubuntu 17.10 was released on 19 October 2017.

If you are coming from Zesty Zapus a.k.a. Ubuntu 17.04, or earlier,
there's a few showstoppers at the moment which affect compiling
Trompeloeil on Artful.

"libstdc++-4.8-dev:amd64 4.8.5-4ubuntu6 configured without _GLIBCXX_USE_C99"
https://bugs.launchpad.net/ubuntu/+source/gcc-4.8/+bug/1725847
Failure mode: `std::to_string()` not defined.

"libstdc++-5-dev:amd64 5.5.0-1ubuntu1 configured without _GLIBCXX_USE_C99"
https://bugs.launchpad.net/ubuntu/+source/gcc-5/+bug/1725848
Failure mode: `std::to_string()` not defined.

"libc++-dev:amd64 3.9.1-3 expects /usr/include/xlocale.h to be installed"
https://bugs.launchpad.net/ubuntu/+source/libc++/+bug/1725858
Failure mode: Using `libc++` fails when including `<ios>`

"libc6-dev:amd64 (2.26-0ubuntu2) has unusable signbit for C++ programs"
https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1725869
Failure mode: `signbit()` macro fails to compile (g++-4.8, g++-5)

In reality, the scope of these issues may prevent many more C++ libraries
from being used with Artful in its present form.

Hopefully new packages for `g++-4.8`, `g++-5`, `libc6-dev`, and `libstdc++-dev` will
be released soon that will allow Trompeloeil to be even more useful on Artful.

**Comment by rollbear** [comment]
These problems are not present when using the more up to date toolchains, though. g++-6, g++-7, clang++-4, and clang++-5.0 all work fine.

**Comment by AndrewPaxie** [comment]
Yes, that is a good point.  However, all combinations were working on Zesty Zapus, so the result is surprising.

**Comment by rollbear** [comment]
Shall we close this as being irrelevant now? 17.10 is not an LTS and reached its end of life 3 years ago.
