### ISSUE TITLE
Conan package

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [rollbear/trompeloeil#72]
Hello,
Do you know about [Conan](https://github.com/conan-io/conan)?
[Conan](http://docs.conan.io/en/latest/) is modern dependency manager for C++. And will be great if your library will be available via package manager for other developers.

[Here](https://github.com/bincrafters/conan-templates) you can find example, how you can create package for the library. 

If you have any questions, just ask :-)

**Comment by ArekPiekarz** [comment]
It's strange that you asked him about Conan but didn't even check that it already supported it.
I can also see you are spamming tons of repositories with the same question.

**Comment by ZaMaZaN4iK** [comment]
@ArekPiekarz Just didn't find this package in conan-center repo. But if author prefer own repo - ok, i can close it. Sorry for annoying.

>I can also see you are spamming tons of repositories with the same question.

yep. But it's not a spam. It's just a request for creating a package. For some libraries i create packages by myself.

**Comment by ArekPiekarz** [comment]
> Just didn't find this package in conan-center repo. 

I'm sure you would find it if you tried, it's right there:
https://bintray.com/trompeloeil/trompeloeil/trompeloeil%3Arollbear

It's the second time I see you did this, first in https://github.com/bombela/backward-cpp/issues/93. Note that I'm not the author of any of these projects, just a user.

**Comment by ZaMaZaN4iK** [comment]
I found this repo, you are right. But it's not central repo. And will be fine, if author will contribute his package to the central repo (i mean conan-center).

**Comment by rollbear** [comment]
Trompeloeil is on conan-center, and has been for quite some time.

**Comment by rollbear** [comment]
To be more accurate, Trompeloeil was accepted into conan-center on September 4th of 2017.

Thanks @ArekPiekarz

**Comment by ArekPiekarz** [comment]
By the way I don't have anything against Conan, I think it has a potential to become de facto standard solution to package management for C++. I just didn't like seeing someone not doing their homework before submitting issues.
