### ISSUE TITLE
Guessing signature for method being mocked

### ISSUE THREAD

**Issue by ytimenkov** [rollbear/trompeloeil#73]
When I was looking at modern alternatives to gmock I found this library and another one called Turtle.

One particular thing I liked about Turtle is that it simplifies mocking interfaces by guessing signature from the base class: http://turtle.sourceforge.net/turtle/motivation.html:
```c++
MOCK_BASE_CLASS( mock_view, view ) // declare a 'mock_view' class implementing 'view'
{
    MOCK_METHOD( display, 1 )      // implement the 'display' method from 'view' (taking 1 argument)
};
```

Is this is something achievable in trompeloeil?
I also appreciate small comparison of these 2 frameworks.

**Comment by rollbear** [comment]
I'll look into it. Looks cool. Whatever techniques it uses, though, are unlikely to be an easy fit into the current code in Trompeloeil.

How does it handle overloaded functions?

**Comment by ytimenkov** [comment]
As I understand from source code it passes pointer to the base member function to a trait template (which matches in compile time) which defines `signature_t` type which can be used to extract parameters' types later, with mocked function being declared as something like `result_type<signature_t> mock_func(parameter_type<signature_t, 0> arg0, ...)`.

Of course this doesn't work when parameters are ambiguous, then one has to specify signature explicitly as 3rd parameter:
```c++
MOCK_BASE_CLASS( mock_class, base_class )
{
    MOCK_METHOD( method, 2, void( int, const std::string& ), identifier_1 ) // both the signature and identifier must be specified because of ambiguity due to overloading
    MOCK_METHOD( method, 1, void( float ), identifier_2 )                   // the identifier must differ from the previous one in order to fully disambiguate methods
};
```

**Comment by rollbear** [comment]
I ran some simple experiments, and superficially it looks quite simple to do. I'm sure I'll stumble onto some gotcha, though.

It'll probably take a while, though, since there are some other things that I really needs my attention.

**Comment by rollbear** [comment]
Experimental, and totally undocumented, support is now on the `develop` branch. For usage, lookup the file `test/compiling_tests.hpp` and search for the use of `mock_interface<>`. These are *always* marked `override` so there is no risk for accidentally mocking non-virtual functions. This implementation cannot handle overloads, but I'm not sure how much of a problem that is. It may not be very difficult to solve.

**Comment by rollbear** [comment]
Functionality now in tagged release v30
