### ISSUE TITLE
IMPLEMENT_MOCK documentation incorrect

### ISSUE THREAD

**Issue by rcdailey** [rollbear/trompeloeil#77]
It could just be me, but I want to make sure: The `IMPLEMENT_MOCKn()` documentation seems wrong:

> See also IMPLEMENT_CONST_MOCKn(...) for non-const member functions.
>
> See also MAKE_CONST_MOCKn(...) for const member functions.

I am quoting from the [master version of  reference.md](https://github.com/rollbear/trompeloeil/blob/master/docs/reference.md#IMPLEMENT_MOCKn).

The first says "non-const", but it should be "const" I think. And the difference between `MAKE_` and `IMPLEMENT_` isn't the constness of the function, but rather the method by which we wish to declare a member function mockable right?

**Comment by rollbear** [comment]
Ops. Thanks for your very quick feedback on this. I'll update directly on `master` in a minute or two (won't bump version, though.)
