### ISSUE TITLE
[fixed on master] Error C2066 with VS 2017 15.7.1

### ISSUE THREAD

**Issue by AndrewPaxie** [rollbear/trompeloeil#88]
MSVC 15.7.1 just keeps on giving.

I noticed that AppVeyor reported a build failure on my fork
of Trompeleoil after merging `master` at `V31`.

See AppVeyor build master #5
<https://ci.appveyor.com/project/AndrewPaxie/trompeloeil/build/master%20%235>
built on 19 May 2018, which failed for "Visual Studio 15 2017" with

```text
error C2066: cast to function type is illegal
```

```text
The CXX compiler identification is MSVC 19.14.26428.1
```

It appears that sometime between 7 May and 19 May AppVeyor upgraded
to Microsoft Visual Studio 15.7.1.  The previous results were

AppVeyor build #4
<https://ci.appveyor.com/project/AndrewPaxie/trompeloeil/build/appveyor%20%234>
built on 7 May 2018, and the compiler appeared to be

```text
The CXX compiler identification is MSVC 19.13.26129.0
```

With this compiler all configurations passed.

After reducing the code, I found the following fragment fails

```cpp
template <typename T>
struct S
{
  using trompeloeil_sig = void(int); // C2066 (vexing parse?)
};
```

This is the `trompeoleil_sig` that
was introduced as a workaround in issue #82.

We now have workarounds for our workarounds, namely this code compiles

```cpp
template <typename T>
struct identity_type
{
  using type = T;
};

template <typename T>
struct S
{
  using trompeloeil_sig = typename identity_type<void(int)>::type;
};
```

I have raised this issue with Microsoft,
["C2066 with type alias declaration in class template"](
https://developercommunity.visualstudio.com/content/problem/256712/c2066-with-type-alias-declaration-in-class-templat.html
)

A fix to `trompeleoil_sig` is suggested by the workaround above,
but will need a suitably pithy comment and some refinement to
reflect the namespace that `identity_type` comes from.

Regression testing may show some further issues.

**Comment by rollbear** [comment]
Sigh. Please add the fix to this (and an entry in ChangeLog, directly on master) so that people that just clones the repo gets something that works. We'll keep the issue open until included in a tagged release.
